### ISSUE TITLE
[Feature] Both Scheduleis and DolphinScheduler dispatching centers are supported

### ISSUE THREAD

**Issue by utopianet** [WeBankFinTech/DataSphereStudio#1008]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

At present, the scheduling center in the workflow can only support one scheduling tool at the same time, and cannot support both.
目前工作流中的调度中心，仅能同时支持其中一种调度工具的调度中心，无法同时支持二种。

### Description

Since there is only one parameter of the dispatching center, the dispatching center cannot support two kinds of dispatching at the same time.
由于调度中心参数只有一个，故无法同时支持二种调度的调度中心同时存在。

It is expected that new parameters can be added to support the dispatching center function of using two types of dispatching at the same time.
期望能新增参数，支持同时使用二种调度的调度中心功能。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wushengyeyouya** [comment]
A project only support one type Scheduler, but different project can support the different schedulers.
