### ISSUE TITLE
[Feature] compatiable with linkis 1.3.1

### ISSUE THREAD

**Issue by jackxu2011** [WeBankFinTech/DataSphereStudio#1013]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

1. dss-flow-execution-server miss linkis-scheduler scheduler.
```
        <dependency>
            <groupId>org.apache.linkis</groupId>
            <artifactId>linkis-scheduler</artifactId>
            <version>${linkis.version}</version>
        </dependency>
```

2.  dss-orchestrator/orchestrators/dss-workflow/dss-flow-execution-server/src/main/java/com/webank/wedatasphere/dss/flow/execution/entrance/persistence/WorkflowPersistenceEngine.java
should remove the subJob related methods

```
@Override
    public void persist(SubJobInfo subjobInfo) throws ErrorException {

    }
 @Override
    public void updateIfNeeded(SubJobInfo subJobInfo) throws ErrorException {

    }

    @Override
    public SubJobDetail retrieveJobDetailReq(Long jobDetailId) throws ErrorException {
        return null;
    }

```

### Description

no

### Use case

no

### solutions

no

### Anything else

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wushengyeyouya** [comment]
Thanks
