### ISSUE TITLE
发布后的API,在点击更新API时,无法弹出更新API的模态框

### ISSUE THREAD

**Issue by fqm12321** [WeBankFinTech/DataSphereStudio#1014]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar issues.

### DSS Component

dss-apps/dss-apiservice

### What happened + What you expected to happen

![image](https://user-images.githubusercontent.com/21233240/209896973-f7b823ce-2f95-440c-95b6-d677ad790cb2.png)

### Relevent platform

linkis 1.1.1
dss基于 dev-1.2.0-atlas分支打的包

### Reproduction script

无

### Anything else

后端没有报错,approvalName这个在数据库中确实没有保存,后端代码已注释掉该值

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by fqm12321** [comment]
接口状态码判断有误,
![ce01ffed567cd8f661e7d39b535de5c](https://user-images.githubusercontent.com/21233240/209897652-d9bd97ae-d140-4652-bb02-c026f4784530.png)
![2810a67ba2ca20f7aa573de36b2c012](https://user-images.githubusercontent.com/21233240/209897660-977c0e47-fc87-406e-8587-ea10fccff0ac.png)

**Comment by jiangxch** [comment]
解决了吗
