### ISSUE TITLE
[Feature] 请问有没有数据安全组件的版本规划，支持数据加密、脱敏等功能

### ISSUE THREAD

**Issue by patience00** [WeBankFinTech/DataSphereStudio#1030]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wushengyeyouya** [comment]
Hi, welcome to achieve it with community!
