### ISSUE TITLE
[Bug] add user error

### ISSUE THREAD

**Issue by xiaofan2022** [WeBankFinTech/DataSphereStudio#1043]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar issues.

### DSS Component

dss-web/framework

### What happened + What you expected to happen

1. An error occurred when adding a user using the hadoop Management source account. {"method":null,"status":1,"message":"java.naming.provider.url property does not contain a URL","data":{"rows":0}}
2. Succeeded in adding an account
3. curl "http://103.29.16.199:8085/api/rest_j/v1/dss/framework/admin/user/add" ^
  -H "Accept: application/json, text/plain, */*" ^
  -H "Accept-Language: zh-CN,zh;q=0.9,or;q=0.8" ^
  -H "Connection: keep-alive" ^
  -H "Content-Type: application/json;charset=UTF-8" ^
  -H "Content-language: zh-CN" ^
  ``````
  --data-raw "^{^\^"deptId^\^":100,^\^"userName^\^":^\^"root^\^",^\^"name^\^":^\^"root^\^",^\^"password^\^":^\^"*^\^",^\^"phonenumber^\^":^\^"^\^",^\^"email^\^":^\^"^\^"^}" ^
  --compressed ^
  --insecure

response:
{"method":null,"status":1,"message":"java.naming.provider.url property does not contain a URL","data":{"rows":0}}


### Relevent platform

linkis1.3.1
dss1.1.1

### Reproduction script

Click Add user

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wushengyeyouya** [comment]
Please set the LDAP configurations.
