### ISSUE TITLE
[Feature]能否和hadoop环境解绑

### ISSUE THREAD

**Issue by ecit-zzh** [WeBankFinTech/DataSphereStudio#1044]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

大数据技术路线除了hadoop技术外，还有MPP技术路线(如以StarRocks为核心的数据平台)。目前DSS底层依赖hadoop环境，无法适用于仅有MPP技术组件而没有hadoop环境的数据平台。

### Description

所以DSS能否和hadoop解耦，使DSS成为一个更加通用的计算中间件。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wushengyeyouya** [comment]
Linkis has support to install without Hadoop, you can install it with this doc: https://linkis.apache.org/zh-CN/docs/1.4.0/quick/deploy-without-hdfs
