### ISSUE TITLE
[Feature] DSS 1.1.1 如何在数据交换中使用datax做数据同步？

### ISSUE THREAD

**Issue by heartk** [WeBankFinTech/DataSphereStudio#1048]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

DSS 1.3.1 如何在数据交换中使用datax做数据同步？

### Description

能否像写帮助文档一样，一步一步的详细说明 DSS-1.1.1  linkis-1.3.1 Exchangis-1.0.0 如何集成datax, 包括支持datax的版本，中间使用的plugin 或者 engine 的版本是从哪里下载或者编译的，然后拷贝到哪个项目的哪个目录下，都修改了哪个路径下的哪个配置文件

### Use case

要是能有每个步骤是否生效的验证方法 ，用一个生效的流程和例子就更好了。非常感谢~

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by wushengyeyouya** [comment]
The latest version will support it.
