### ISSUE TITLE
[Bug] Browser version detection alarm

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1049]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar issues.

### DSS Component

dss-web/workspace

### What happened + What you expected to happen

Using the 64.0.3282 version of the browser will cause a too laggy problem (the database table cache has been cleared, the login password is entered, and operations such as right clicking the table are stuck)

### Relevent platform

Google Chrome 64.0.3282

### Reproduction script

None involved

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Fix it in DSS1.1.2
