### ISSUE TITLE
[Feature] Enter the workflow editing page, and the left project bar can switch to display personal projects and all projects

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1050]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

Currently entering the workflow editing page, all items that the user has permission to access will be listed on the left, and the workflow will display all items. For administrators or users with many personal projects, having too many projects can make it difficult to find the required projects. Therefore, consider adding personal projects, shared projects, drop-down filter boxes for all projects, and adding workflow sorting that allows sorting by modification time and name.

### Description

After entering the workflow editing page, add a new item in the upper left corner
1. For personal projects, all projects, and shared projects, select from the drop-down box. For the selected filter, it should be marked in blue to prompt the user, The default selected filter criteria are the same as before the user enters the DSS homepage (i.e., if the user selects an item and enters the workflow editing page, the filter criteria on the DSS homepage is "personal item", then the filter criteria after entering is also "personal item"; if the filter criteria on the homepage is "all items" before entering the workflow editing page, then the user enters the editing page, and the filter criteria are "all items")
2. Sort function, sort by modification time and name, and indicate the selected sorting mode in blue to prompt the user.
The original sorting logic is that the items displayed at the top of the editing page are the items selected by the user before entering the editing page, and the remaining items are sorted according to the modification time.
The new feature retains the original logic, that is, regardless of whether the user selects "sort by modification time" or "sort by name" as the sorting criteria on the homepage before entering the workflow editing page, the selected items on the homepage will be placed at the top after entering the editing page, and the remaining items will be sorted by modification time.
If the user needs to sort again after entering the editing page, the project sorting logic depends on whether the user selects "By modification time" or "By name"

### Use case

no

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
