### ISSUE TITLE
[Feature] DSS log exception optimization, associated error codes or code optimization, restful interface log printing input parameters

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1051]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

1. Optimizing the printing of dss logs is beneficial for subsequent operation and maintenance handover, reducing the difficulty of troubleshooting problems.
2. When calling the restful interface, it is necessary to print the input log and the end log to facilitate the troubleshooting and positioning of log issues.

### Description

For some exceptions thrown, users may not know the solution. For these exceptions, an error code solution needs to be associated. For other exceptions or errors, optimize the log printing in the code.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
