### ISSUE TITLE
[Feature] When creating a new project, the project name is checked as it is entered

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1053]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

When creating a project in DSS, when you enter the relevant information of the project and click "confirm", sometimes an error message "duplicate project name" will be prompted, which can cause users to spend a lot of time filling in the relevant information, but additional time is wasted due to incorrect project name filling.

### Description

After the user enters the project name, the name will be verified. If the project name is duplicate with the existing project name, a prompt will be given directly

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
