### ISSUE TITLE
[Feature] The numbers in the Scriptis floating window now display the number of tasks, which needs to be adjusted to display the number of engines

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1054]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

The user logs in to Scriptis, clicks the Scriptis floating window, and when selecting "Task manager", the interface will be called to obtain the unfinished historical tasks. This version needs to replace the calling interface with the latest interface provided by Linkis.
The numbers in the Scriptis floating window now display the number of tasks, which needs to be adjusted to display the number of engines.

### Description

Original interface call：api/rest_j/v1/jobhistory/list
Current interface call：/api/rest_j/v1/jobhistory/listundonetasks
Interface documentation can be referenced：[listundonetasks](https://linkis.apache.org/docs/1.1.3/api/http/linkis-ps-publicservice-api/jobhistory-api/)
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/8d67e094-51b1-4634-9b2c-031c2ae1a3cb)

Scriptis floating window displays the number of engines, not the number of tasks：
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/f41f8779-0b2d-4d56-8823-ae9857e17918)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
