### ISSUE TITLE
[Feature] Add Tsql（trino） type script

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1056]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

The development of the Linkis Trino engine has been completed, and it is necessary to add a tsql type script in Scriptis. Users can create a tsql type script and submit the written SQL to Trino for execution.

### Description

When creating a new script file, users can select the "Tsql" type in the "Script Type", and the corresponding script name has the suffix ". tsql";
After creating a new tsql type script, display the trino type script icon in front of the script file in the scriptis workspace.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
