### ISSUE TITLE
[Feature] DSS task flow supports recognition of ${run_today_h}, datachecker: supports recognition of ${run_today_h}

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1057]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

Add a new date variable to enable the task to obtain the hour of the scheduled time

### Description

<table>
<tr>
<td>Variable name</td>
<td>illustrate</td>
<td>example</td>
</tr>
<tr>
<td>run_today_h</td>
<td>Indicates the hour when the workflow is currently started </td>
<td>2022051915</td>
</tr>
<tr>
<td>run_today_h_std</td>
<td>Represents the hour standardized format currently invoked by the workflow </td>
<td>2022-05-19 15</td>
</tr>
</table>

Application Scenario
1. Datachekcer performs database table checks
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/7e4cb985-7837-40c9-baae-db7c218af288)

2. Sendmail email header
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/4519851a-a734-4dd5-a056-a478f2fe8614)

3. Batch scheduling after publishing to schedulis

### solutions

1. Reuse variables from Linkis to replace the VariableUtils class for unified variable replacement. We need to synchronize and modify on the linkis side.
2. The workflow nodes of DSS, such as DataCheck  SendEmail, need to support this variable.
3. Synchronize modifications to the schedulis plugin jobType.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
