### ISSUE TITLE
[Feature] The horizontal drag bar below the workflow editing interface is obscured and cannot be seen by the user

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1061]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

The user cannot see the horizontal drag button of DSS in the workflow interface, thinking that the operation is not supported.

### Description

1. Currently, there are horizontal drag buttons, which are obscured by the toolbar where the publishing history is located after being displayed.
2. Optimize the toolbar display below and change it to the default shrink state, allowing users to click on it themselves.
3. Current display
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/ac0a5258-1789-4244-8f04-e9676ccbbd6b)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
