### ISSUE TITLE
[Feature] The user joins two workspaces by default

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1063]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

After logging in to the DSS, a new user is added to the bdapWorkspace_0X workspace by default. Therefore, you need to add the user to the bdapWorkspace workspace

### Description

Join bdapWorkspace_ 0X and bdapWorkspace workspaces at the same time  when new users log in.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
