### ISSUE TITLE
[Feature] Support elongating field names when viewing table details and field information

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1066]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

Unable to see complete field names in the table details
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/eb338230-9a37-4639-a7d8-87ff5cbbbcb3)

### Description

Change to a similar effect to the Scriptis result set, where users can automatically stretch and shrink the display size of corresponding fields
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/5e566fbd-3c49-4d34-9a24-327a5e9cc05d)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
