### ISSUE TITLE
[Feature] Scriptis engine management page with arrow in the bottom right corner, add button: select all idle engines

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1070]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Description

![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/4800bde4-09ac-4141-8e23-5f15322b75b3)

This requirement involves duplicate code in both the dss scriptis and linkis management consoles, so dss scriptis only needs to migrate the front-end code of the linkis management console.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
