### ISSUE TITLE
[Bug] Schedulis Optimized for log printing, only the first 1024 characters are printed

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1072]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar issues.

### DSS Component

dss-appconn

### What happened + What you expected to happen

Now the result sets of some task logs of the schedulis are printed too long, affecting the wtss task log view, and the optimization is to limit the print result set to the first 1024 characters.
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/4aca7a43-07c5-4c26-93c2-46ef4a477fee)

### Relevent platform

no

### Reproduction script

no

### Anything else

After calling getLinkisNodeExecution().getresult () in the run() method of the AzkabanDssJobType class to obtain the linkis result set, print the first 1024 characters for each result set.

Modification point:
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/de451d86-0f00-44a2-ba2d-4ae3168f0cc6)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Fix it in DSS1.1.2
