### ISSUE TITLE
[Feature] Optimize error information and log display logic

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1073]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

If the task status is completed but failed, an error message is displayed on the Progress page. If you want to view the specific error logs, click Log under Progress to view the specific error logs. Error log viewing experience improved.

### Description

If the Error code is not bound to the solution, when the task fails, the user directly opens the error log at the lower part of the page and locates the error location.
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/05e63f6e-7342-4e94-ba38-7ee7fa0d7ce1)

If the error code is bound to the solution, the progress page is displayed at the bottom of the page when the task fails. You can click to view the solution associated with the error code.
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/14543e25-4bfd-4311-8f8f-f539f916eda2)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
