### ISSUE TITLE
[Feature] Batch deletion of tables in the database supports selecting all during secondary review

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1074]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

The current user needs to double check when deleting their own created tables in bulk, and feedback is that there is a need to add a select all function.

### Description

Batch deletion is supported during the second review
During the second review, it is currently necessary to check each table one by one and add a batch of check boxes for deletion.
All selected tables to be deleted can be scrolled through, and by clicking on the Select All box above, all tables can be selected. As cross page multiple selection is not currently supported, up to 20 records can be selected for batch deletion.
Currently, it is not supported to cross page check the tables to be deleted, or to batch delete more than 20 tables.
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/afd455e4-a232-4664-9e5b-641ddbb3e8cc)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
