### ISSUE TITLE
[Feature] Configures the administrator's default viewing rights for workspace items

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1075]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

As a result of organizational changes, there are users from other departments in their workspace.   Therefore, if an administrator has access to all projects, code leaks may occur.   You want your workspace to be set to remove administrator access to all projects.

### Description

Added workspace level properties: Whether workspace administrators have permission to view all projects by default.
If you have permission, the administrator can view all projects by default. If no, you do not have the permission to view all projects 
 by default.
【 Workspace Management 】-【 Basic Information 】 displays the new attribute "Administrator selects all projects in the workspace by default", the value is "Viewable" or "not viewable".
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/a3faae69-ced7-4a3c-ade1-fd50189483bd)

### solutions

1. Add the field admin_permission of tinyint type to the table dss_workspace. The default value is 1, which is used to determine whether all items in the workspace can be viewed by the administrator of the workspace. If the value is 1, it can be viewed, and 0 indicates that it cannot be viewed. At this point, the workspace administrator can only view the projects that it has created.
2. When calling interface/dss/framework/workspace/workspaces/{id}, the return value is represented by the parameter admin_ Permission to control the administrator's default viewing permissions for all projects in the workspace. When the value is 1, the display is viewable, and when it is 0, the display is not viewable
3. When calling the interface/dss/framework/project/getAllProjects to obtain projects that users can view, the backend will control whether to return all projects.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
