### ISSUE TITLE
[Feature] When viewing the table structure, the partition information displays content adaptively on the screen, covering the page

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1076]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

The partition information display for the current version is fixed at 400, resulting in a large amount of blank pages and a poor user experience that needs optimization. The optimized partition information display can adaptively fill the page.

### solutions

Modify the display logic of the display area and adapt the page.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
