### ISSUE TITLE
[Feature] New user guidance optimization

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1077]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Description

**Pop up prompt for new users entering Scriptis**

1. When the user has not completed initialization, enter Scriptis and a pop-up window saying 'User has not completed initialization' will appear. The previous error message in the upper right corner still exists (an error message indicating that the root directory of the user's local workspace does not exist), and [View Application Guidelines] is associated with the document of the user's bill of lading in the knowledge base.
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/406058d0-4ba6-4076-9e6f-541f077c5b0b)

2. After completing initialization, the user enters Scriptis. If the user enters the Scriptis page for the first time, a pop-up window displaying usage instructions will be displayed for the user. If the user is not logged in for the first time, the pop-up window will no longer be displayed for the user.
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/406ca798-d925-41e2-b83d-30d4bee3fc6b)

**Popup display logic sorting:**
Real name user scenario:
Real name user has not completed initialization ->Display incomplete initialization pop-up, do not display usage guidance pop-up
Real name user completes initialization and enters Scriptis for the first time ->Display usage guide pop-up window
Real name user has completed initialization and is not the first time entering Scriptis ->Do not display pop-up window
Proxy User Scenario:
Proxy user has not completed initialization ->Display incomplete initialization pop-up, do not display usage guidance pop-up
Proxy user completes initialization and real name user enters Scriptis for the first time ->Display usage guide pop-up window
Proxy user has completed initialization and real name user is not the first time entering Scriptis ->Do not display pop-up window

**interactive**
If the user has not completed initialization, a pop-up window will pop up for the user every time they enter
If the user has completed initialization, click on 'I understand' and the upper right corner“ ×”， You can close the pop-up window and click 'Quick Use Scriptis' to open the Scriptis usage guide document on a new page.
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/21bc04a0-fe6a-43fb-91f5-705ae578031b)

**Script type display optimization**
Sql -> Spark Sql
Hive -> Hive Sql
Psql -> Presto Sql
Tsql -> Trino Sql
Flink -> Flink Sql
Scala -> Spark Scala
The other script types not listed are unchanged
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/9d8ff840-c51d-4a5c-a9b5-4530611aab15)

### solutions

Once in scriptis, trigger the backend interface to get the current user's stage.

If it is uninited, the current user has not completed the initialization, and the user initialization guide is displayed.

If it is new, the user is new, but initialization has been completed, and scriptis quick Guide popup.

If it is senior, it indicates that the user is an old user, and no popup window is displayed.

![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/876d6779-30cd-4f5d-a013-8b89edfb1811)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
