### ISSUE TITLE
demo版本登录后 点击schedulis 跳转至登录页

### ISSUE THREAD

**Issue by fasoal** [WeBankFinTech/DataSphereStudio#108]
![image](https://user-images.githubusercontent.com/14243815/74822414-0d0a1b80-5340-11ea-8a6d-8f45251a9662.png)
![image](https://user-images.githubusercontent.com/14243815/74822371-fc59a580-533f-11ea-9103-cf350068055f.png)

**Comment by peacewong** [comment]
For security reasons, schdulis does not provide a Demo environment. You can install and deploy this feature.
