### ISSUE TITLE
[Feature] linkis-appconn-engineplugin module removes linkis dependency

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1081]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

At present, the linkis-appconn-engineplugin module of dss is dependent on linkis. As a result, the module cannot be relied on by linkis due to cyclic dependency, so the lib package related to the module cannot be placed on the machine of linkis through standard project construction. The current way is to package and build the module on the dss side, and manually copy the relevant lib package to the linkis machine by copying zip when it is released, which is not reasonable.

### Description

It is necessary to remove the dependency of linkis-appconn-engineplugin module of dss on linkis, so that linkis can rely on this module, and then distribute the lib package related to this module to linkis machine through standard maven project construction mode to optimize the operation and maintenance process.

### solutions

Removing linkis dependency in linkis-appconn-engineplugin module.
linkis relies on the Linkis-Appconn-Engineplugin module of dss to package the relevant jar packages into the linkis service.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
