### ISSUE TITLE
[Feature] After the scriptis page is refreshed, the front-end repeatedly calls the same interface optimization

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1082]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

After scriptis refresh, front-end repeatedly asked interface/API/rest_j/v1 / DSS/framework/workspace/getWorkspaceUsers? workspaceId=266

api/rest_j/v1/dss/apiservice/getUserServices? workspaceId=266, which on the one hand consumes performance, on the other hand, if the two interfaces report an error, this will cause several columns to repeat the error message bombardment.

Therefore, the front-end needs to optimize the interface call, remove unnecessary interface calls, and avoid frequent interface calls.

### Description

Optimize calls to the above two interfaces so that no repeated requests are made when scriptis page refreshes

### solutions

Repeated requests are sent because each script in the publish data service sends related requests

Modify the request sending logic so that the request is sent only once when the page is refreshed

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
