### ISSUE TITLE
[Feature] Optimize error messages thrown by schedulis

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1083]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

Nodes in the schedulis project are not allowed to have the same name. When the same name occurs, the error message of the schedulis is not clear, which is difficult for users to understand. Therefore, the error message of the schedulis needs to be parsed, and the expression of the error message needs to be reorganized before it is returned to the user.

### Description

As a DSS user, enter the project "test" in DSS, create a new workflow with a node named "start" in the workflow, save the workflow, and publish it.

The same user enters the project "test" again in DSS, creates a new workflow again, has a node named "start", and the node name of the previous workflow, saves the workflow, and then publishes it. You will see "Release failed. The workflow node start has the same name as another workflow node in the project, please rename the node ".

### solutions

1. Subject logic

1). In SchedulisAppConn, detect the error returned by the schedulis, and if the error copy contains "has ambiguous dependency", the user is prompted to "publish failed". Workflow node ${node name} has the same name as another workflow node in this project. Please rename the node.

2). Node names are extracted through regular matching.

2. Interface design
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/9ce9dd00-1594-426c-9c6f-a8466f612808)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
