### ISSUE TITLE
[Feature] The error message reminder box is displayed permanently

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1084]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

When a user uses a function on the DSS, if the operation is incorrect or the status is failed, an error notification box will be displayed in the upper right corner of the page for 3 to 5s.  If the error information is more complex, the popup window will automatically disappear before the user has time to read the error information, which is not conducive to the troubleshooting of users and operation and maintenance colleagues.

### Description

**Error messages are displayed permanently**

Error message display logic:

If the mouse does not move to the error notification box, it will disappear automatically after 5 6s.
Move the mouse over the error notification reminder box, and the reminder box permanently displays. Users can click "×" to close the reminder box (or click "Report error"/" View solution ", or refresh the page);
Note: 1) As long as the mouse moves to the reminder box, even after it is removed, the prompt box will be permanently displayed, and the closing method is described above; 2) When there are multiple error boxes, the logic is consistent with the single error box

### solutions

Two realization schemes are designed according to the product:

1: All error messages are displayed permanently. Modify the configuration of the interface error notice and do not automatically close it

2: The user moves the mouse to the error message to block the shutdown. After blocking the shutdown, you need to manually close it. The mouse event mouseover is monitored to the error prompt area, and the onClsoe is blocked when it is closed incorrectly

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
