### ISSUE TITLE
[Feature] Clean up downloaded lib packages when the appconn engine exits

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1085]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

After the appconn engine exits, the downloaded appconn packages will not be automatically cleaned up in the engine directory, resulting in an increasing disk space usage. I hope that after optimization, the lib package downloaded by appconn can be automatically deleted when the engine exits.

### Description

Due to the fact that the dss-appconns directory is not softlinked to public resources, each engine will download a new directory, resulting in disk usage. Therefore, when the appconn engine exits, it is necessary to clean the dss appconns directory.

### solutions

1. Rewrite the hook method (ComputationExecutor. tryShutdown()) when the linkis engine exits in the AppConnEngineConnExecutor class, and add appconn's lib directory cleaning logic to this method.
2. Reuse the AppConnUtils. getAppConnHomePath() method of existing tool classes to obtain the root directory of the appconn engine

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
