### ISSUE TITLE
[Feature] Workflow node name display optimization

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1086]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

The current workflow node displays a maximum of 12 characters. You can view more characters only by enlarging the workflow.

**Current workflow situation**
1. The workflow structure is complex and the number of nodes is large
2. Workflow node names are long (40+ characters)

**Detailed description**
1. There are a lot of workflow nodes (hundreds) in the stock of work flow, and the current connection is unformatted (formatting will put the table of the same level in one row, which may lead to a very wide width of the entire workflow, which is inconvenient to query).
2. Many nodes are named after the specification of the topic domain _ layer _ number _xxx.

**analyze**
Do not change the maximum width of the current node as much as possible: for some complex workflows, node positions and connections are manually dragged by users, if the default node width is increased, the node positions in the inventory of workflows may coincide;

### Description

Increase the number of characters displayed without adjusting the width of the default workflow nodes.

The current workflow nodes A,B,C three parts can display more characters, where the C part needs to be reserved for the icon of the execution state. Therefore, you can use parts A and B to show as many characters as possible.
(The width of each character is different, so the number of displayed characters cannot be clearly given)
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/95298a6b-bedb-46a0-90e9-f4ee4b2ebcca)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
