### ISSUE TITLE
[Feature] An isMicroApp field is added to the appconns interface to indicate the micro application

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1087]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

The pages of DSS can be embedded into third-party applications. Due to historical reasons, early applications were all embedded in iframes. Later, after technological transformation, some applications were upgraded to micro application methods. However, due to human scheduling and other reasons, not all applications have completed micro application modifications, so currently there are two types of embedding methods coexisting. In order for the front-end to better identify which method the application is embedded through, it is necessary to mark the embedding method of the application when obtaining the application menu.

### Description

As a DSS user, after logging in to DSS, click the Product menu button in the upper left corner to open the product menu and trigger the front-end interface.

The front-end invokes the interface to obtain the appconn information that has been added to the DSS, and the DSS back-end returns the appconn information, in which a field is isMicroApp.

The user clicks the menu and enters an application. The front-end determines whether the application is a micro application by the value of isMicroApp field of appconn information corresponding to the menu. If yes, the application is rendered as a micro application.

### solutions

1. Main logic:

1). The data on the left menu of dss is obtained from the appconns interface. Add an isMicroApp field to this interface, isMicroApp=true indicates micro application, isMicroApp=false or no such field indicates non-micro application.

2). Add a is_micro_app field to the dss_appconn table to record whether appconn is a micro front-end.

3). Every time the appconn information is obtained, the value of is_micro_app field is found in the dss_appconn table and returned to the front-end.

4). The front-end passes the isMicroApp result and decides how to render it.

2. Time sequence diagram
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/c21b37d5-55e0-459f-9ee9-f0a9564dc4bd)

3. Design the front and rear interfaces
Interface path:/api/rest_j/_v1/dss/framework/workspace/workspaces/{workspaceId}/appconns

![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/d2a3f224-ff2f-44ab-b165-0adfbc6d0822)

![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/5758a96d-1e43-4af1-9ef5-d1bd477e3b63)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
