### ISSUE TITLE
[Feature] Add bulletin board

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1089]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

When updating the current version and upgrading the system, it mainly relies on sending upgrade notifications within the user group to let users know the information. However, the scope of group message notifications is limited, and some users cannot obtain information about system upgrades. Therefore, it is necessary to add channels for announcement notifications within the product website, so that users can quickly obtain information.

### Description

1. Developers should write a notice that includes three elements: the effective time, the end time, and the content of the notice, and write a change SQL to synchronize with the production environment.
2. The operation and maintenance personnel execute the SQL for announcement publishing to achieve announcement publishing.
3. On the DSS homepage, prominently display the announcement content.

### solutions

This function involves the configuration, display, effectiveness, and expiration of announcements, both on the scriptis homepage and the dss homepage. In terms of functional structure, there is no difference between scriptis and dss, so starting from the secondary module, their functional structure is identical.
**Announcement Configuration**
The announcement configuration is completed by the operation and maintenance personnel. Every time an announcement needs to be published, the developers will write the SQL for the announcement, and the operation and maintenance personnel will execute the changes to complete the announcement.
**Announcement takes effect**
By comparing the startTime configured for the announcement with the current time, if the startTime is earlier than or equal to the current time, the announcement will take effect; otherwise, the announcement will not take effect.
**Announcement Invalidation**
By comparing the endTime configured for the announcement with the current time, if the startTime is earlier than or equal to the current time, the announcement will take effect; otherwise, the announcement will not take effect.
**Announcement display**
Extract the content of the announcement from the database and determine its effectiveness and expiration status. If the announcement is within the effective period and has expired, the announcement will be displayed. Otherwise, it will not be displayed.

**Database design**
```
CREATE TABLE `dss_notice`
(
    `id`          int(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary key ID',
    `content`   text DEFAULT NULL COMMENT 'Announcement content',
    `start_time` datetime    DEFAULT CURRENT_TIMESTAMP COMMENT 'Effective time',
    `end_time`  datetime    DEFAULT CURRENT_TIMESTAMP COMMENT 'Failure time',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='Home Announcement Content';
```

**interface design**
DSS obtains homepage notification announcement,Interface path:/api/rest_j/v1/dss/framework/workspace/getNotice
Return data
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/65f9a64e-cebf-4b27-9fe6-88763783da4e)
Scriptis obtains the homepage notification announcement interface ,Interface path:/api/rest_j/v1/dss/scriptis/getNotice
Return data
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/2f2dc126-c0b8-4c7b-830c-ae4ccb70670c)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
