### ISSUE TITLE
[Bug] Fix the issue of workflow name and project name being too long

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1090]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar issues.

### DSS Component

dss-orchestrator

### What happened + What you expected to happen

The workflow name has been adjusted to 150 characters, but the modified node still displays a maximum of 128 characters.

The length limit for node names for modification and creation is 150 characters.

### Relevent platform

no

### Reproduction script

no

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by wxyn** [comment]
Adjust the value on dss_workflow_node_ui_validate to 150 characters.

**Comment by zqburde** [comment]
Fix it in DSS1.1.2
