### ISSUE TITLE
[Feature] Linkis jobtype plugin log printing optimization

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1091]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

On the scheduling side, we now want to obtain real-time execution logs of the Linkis task to filter the taskId. Currently, the Linkis plugin does not use methods such as the information provided by the parent class AbstractJob in scheduling to print job logs. Therefore, scheduling cannot obtain real-time log information. Please modify the log printing method here.

### solutions

Modify the log printing method of the plugin JobType and use the info method of the parent class AbstractJob provided by schedulis to enable schedulis to obtain real-time log information

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
