### ISSUE TITLE
[Feature] Library table information page, batch transfer table function added with select all button

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1092]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

When you select the tables that you want to delete or transfer in batches on the details page of the library, you need to select them one by one, which is inefficient. Therefore, you need to select them in batches.

### Description

The library table information page supports batch selection of all tables.

All boxes are added to the library table information page. Users can select all tables displayed on the current page by selecting all boxes. The interaction logic must be consistent with other select all logic.
Select All Select all for the content displayed on the current page.

![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/6b68652c-b99c-4e8a-b75e-b4932c6f8309)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
