### ISSUE TITLE
[Feature] Consolidation of background Microservices

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1096]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

The current DSS development center service includes 8 processes, and the production center service includes two processes. The number of processes is too many and the operation and maintenance is difficult, so Microservices need to be merged.

### Description

Merge the existing dss-apiservice-server, dss-datapipe-server, dss-scriptis-server, dss-guide-server four independent app services into one dss-apps-server service. Merge dss-framework-orchestrator-server, dss-flow-entrance, and dss-workflow-server into dss-framework-orchestrator-server. Modify the corresponding start and stop scripts and cicd process simultaneously.

### solutions

**1. Overall design**

1. Merge the lib directory of the existing dss-apiservice-server, dss-datapipe-server, dss-scriptis-server, and dss-guide-server independent app services into the new dss-apps-server Services. Merge dss-framework-project-server, dss-framework-orchestrator-server, dss-flow-entrance, and dss-workflow-server into dss-server. The remote rpc call between services needs to be changed to the local rpc call.
<html>
<body>
<span data-shimo-docs="[[30,[{&quot;A1&quot;:[40,[[20,&quot;合并前\n&quot;]],&quot;5:2|6:1&quot;],&quot;B1&quot;:[40,[[20,&quot;project-server\n&quot;]]],&quot;C1&quot;:[40,[[20,&quot;orchestrator-dev\n&quot;]]],&quot;D1&quot;:[40,[[20,&quot;workflow-server-dev\n&quot;]]],&quot;E1&quot;:[40,[[20,&quot;flow-entrance\n&quot;]]],&quot;F1&quot;:[40,[[20,&quot;apiservice-server\n&quot;]]],&quot;G1&quot;:[40,[[20,&quot;datapipe-server\n&quot;]]],&quot;H1&quot;:[40,[[20,&quot;scriptis-server\n&quot;]]],&quot;I1&quot;:[40,[[20,&quot;guide-server\n&quot;]]],&quot;A2&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B2&quot;:[40,[[20,&quot;\n&quot;]]],&quot;C2&quot;:[40,[[20,&quot;orchestrator-prod\n&quot;]]],&quot;D2&quot;:[40,[[20,&quot;workflow-server-prod\n&quot;]]],&quot;E2&quot;:[40,[[20,&quot;\n&quot;]]],&quot;F2&quot;:[40,[[20,&quot;\n&quot;]]],&quot;G2&quot;:[40,[[20,&quot;\n&quot;]]],&quot;H2&quot;:[40,[[20,&quot;\n&quot;]]],&quot;I2&quot;:[40,[[20,&quot;\n&quot;]]],&quot;A3&quot;:[40,[[20,&quot;合并后\n&quot;]],&quot;5:2|6:1&quot;],&quot;B3&quot;:[40,[[20,&quot;dss-server-dev&quot;],[20,&quot;\n&quot;,&quot;7:1&quot;]],&quot;5:1|6:4|7:1&quot;],&quot;C3&quot;:[40,[[20,&quot;\n&quot;,&quot;7:1&quot;]],&quot;7:1&quot;],&quot;D3&quot;:[40,[[20,&quot;\n&quot;,&quot;7:1&quot;]],&quot;7:1&quot;],&quot;E3&quot;:[40,[[20,&quot;\n&quot;,&quot;7:1&quot;]],&quot;7:1&quot;],&quot;F3&quot;:[40,[[20,&quot;dss-apps-server&quot;],[20,&quot;\n&quot;,&quot;7:1&quot;]],&quot;5:1|6:4|7:1&quot;],&quot;G3&quot;:[40,[[20,&quot;\n&quot;]]],&quot;H3&quot;:[40,[[20,&quot;\n&quot;]]],&quot;I3&quot;:[40,[[20,&quot;\n&quot;]]],&quot;A4&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B4&quot;:[40,[[20,&quot;dss-server-prod&quot;],[20,&quot;\n&quot;,&quot;7:1&quot;]],&quot;5:1|6:4|7:1&quot;],&quot;C4&quot;:[40,[[20,&quot;\n&quot;]]],&quot;D4&quot;:[40,[[20,&quot;\n&quot;]]],&quot;E4&quot;:[40,[[20,&quot;\n&quot;]]],&quot;F4&quot;:[40,[[20,&quot;\n&quot;]]],&quot;G4&quot;:[40,[[20,&quot;\n&quot;]]],&quot;H4&quot;:[40,[[20,&quot;\n&quot;]]],&quot;I4&quot;:[40,[[20,&quot;\n&quot;]]]},[[10,4]],[[10,1,&quot;3:37&quot;],[10,1,&quot;3:71&quot;],[10,1,&quot;3:81&quot;],[10,1,&quot;3:95&quot;],[10,1,&quot;3:80&quot;],[10,1,&quot;3:67&quot;],[10,1,&quot;3:68&quot;],[10,1,&quot;3:53&quot;],[10,1,&quot;3:59&quot;]]],&quot;25:\&quot;ScNlfR\&quot;&quot;]]">

合并前 | project-server | orchestrator-dev | workflow-server-dev | flow-entrance | apiservice-server | datapipe-server | scriptis-server | guide-server
-- | -- | -- | -- | -- | -- | -- | -- | --
  | orchestrator-prod | workflow-server-prod |   |   |   |   |  
合并后 | dss-server-dev | dss-apps-server
dss-server-prod |   |   |   |  

</span>
</body>
</html>

2. Modify the dss interface matching service logic of the DSS-gateway-support module. The interfaces of  dss/framework/project, dss/framework/orchestrator, dss/workflow and dss/flow/entrance forward to dss-server service interface.

3. Develop a new CICD process for the new service structure. Keep all the old processes and create a new set of processes.

1.1 Technical Architecture
<html>
<body>
<span data-shimo-docs="[[30,[{&quot;A1&quot;:[40,[[20,&quot;DataSphereStudio&quot;,&quot;31:3&quot;],[20,&quot;\n&quot;]],&quot;1:\&quot;%23d9d9d9\&quot;|33:0&quot;],&quot;B1&quot;:[40,[[20,&quot;category\n&quot;]],&quot;1:\&quot;%23d9d9d9\&quot;|33:0&quot;],&quot;C1&quot;:[40,[[20,&quot;lectotype\n&quot;]],&quot;1:\&quot;%23d9d9d9\&quot;|33:0&quot;],&quot;D1&quot;:[40,[[20,&quot;version\n&quot;]],&quot;1:\&quot;%23d9d9d9\&quot;|33:0&quot;],&quot;A2&quot;:[40,[[20,&quot;Microservices module\n&quot;]],&quot;33:0|5:11|6:1&quot;],&quot;B2&quot;:[40,[[20,&quot;Microservices governance\n&quot;]],&quot;33:0&quot;],&quot;C2&quot;:[40,[[20,&quot;Spring Cloud&quot;,&quot;31:3|7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D2&quot;:[40,[[20,&quot;Finchley.RELEASE&quot;,&quot;31:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;A3&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B3&quot;:[40,[[20,&quot;Service Registration and Discovery\n&quot;]],&quot;33:0&quot;],&quot;C3&quot;:[40,[[20,&quot;Nacos&quot;,&quot;31:3|7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D3&quot;:[40,[[20,&quot;Not involved yet\n&quot;]],&quot;33:0&quot;],&quot;A4&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B4&quot;:[40,[[20,&quot;Unified Configuration Center\n&quot;]],&quot;33:0&quot;],&quot;C4&quot;:[40,[[20,&quot;Managis&quot;,&quot;31:3|7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D4&quot;:[40,[[20,&quot;1.3.5&quot;,&quot;31:3|7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;A5&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B5&quot;:[40,[[20,&quot;Gateway Routing\n&quot;]],&quot;33:0&quot;],&quot;C5&quot;:[40,[[20,&quot;Spring Cloud Gateway&quot;,&quot;31:3|7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D5&quot;:[40,[[20,&quot;2.0.1.RELEASE&quot;,&quot;31:3|7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;A6&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B6&quot;:[40,[[20,&quot;service call\n&quot;]],&quot;33:0&quot;],&quot;C6&quot;:[40,[[20,&quot;OpenFeign&quot;,&quot;31:3|7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D6&quot;:[40,[[20,&quot;2.0.0.RELEASE&quot;,&quot;31:3|7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;A7&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B7&quot;:[40,[[20,&quot;Service Security Certification\n&quot;]],&quot;33:0&quot;],&quot;C7&quot;:[40,[[20,&quot;UC&quot;,&quot;31:3|7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D7&quot;:[40,[[20,&quot;Under planning\n&quot;]],&quot;33:0&quot;],&quot;A8&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B8&quot;:[40,[[20,&quot;Interface Document Engine\n&quot;]],&quot;33:0&quot;],&quot;C8&quot;:[40,[[20,&quot;GITBOOK(Swagger)&quot;,&quot;31:3|7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D8&quot;:[40,[[20,&quot;Not involved yet\n&quot;]],&quot;33:0&quot;],&quot;A9&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B9&quot;:[40,[[20,&quot;Service application monitoring\n&quot;]],&quot;33:0&quot;],&quot;C9&quot;:[40,[[20,&quot;Spring Cloud Admin&quot;,&quot;31:3|7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D9&quot;:[40,[[20,&quot;Not involved yet\n&quot;]],&quot;33:0&quot;],&quot;A10&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B10&quot;:[40,[[20,&quot;Service Link Tracking\n&quot;]],&quot;33:0&quot;],&quot;C10&quot;:[40,[[20,&quot;Skywalking&quot;,&quot;31:3|7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D10&quot;:[40,[[20,&quot;Under planning\n&quot;]],&quot;33:0&quot;],&quot;A11&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B11&quot;:[40,[[20,&quot;The service is degraded, fused, or restricted\n&quot;]],&quot;33:0&quot;],&quot;C11&quot;:[40,[[20,&quot;Organize and compare &quot;],[20,&quot;Sentinel/Hystrix&quot;,&quot;31:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D11&quot;:[40,[[20,&quot;Under planning\n&quot;]],&quot;33:0&quot;],&quot;A12&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B12&quot;:[40,[[20,&quot;Load balancing between services\n&quot;]],&quot;33:0&quot;],&quot;C12&quot;:[40,[[20,&quot;Spring Cloud ribbon&quot;,&quot;31:3|7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D12&quot;:[40,[[20,&quot;2.0.0.RELEASE&quot;,&quot;31:3|7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;A13&quot;:[40,[[20,&quot;Basic universal module\n&quot;]],&quot;33:0|5:12|6:1&quot;],&quot;B13&quot;:[40,[[20,&quot;database\n&quot;]],&quot;33:0&quot;],&quot;C13&quot;:[40,[[20,&quot;Mysql&quot;,&quot;7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D13&quot;:[40,[[20,&quot;5.1.34(Driver version)\n&quot;]],&quot;33:0&quot;],&quot;A14&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B14&quot;:[40,[[20,&quot;Data access persistence\n&quot;]],&quot;33:0&quot;],&quot;C14&quot;:[40,[[20,&quot;Mybatis&quot;,&quot;7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D14&quot;:[40,[[20,&quot;3.4.6&quot;,&quot;7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;A15&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B15&quot;:[40,[[20,&quot;MVC&quot;,&quot;7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;C15&quot;:[40,[[20,&quot;Spring mvc&quot;,&quot;7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D15&quot;:[40,[[20,&quot;1.19.1&quot;,&quot;7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;A16&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B16&quot;:[40,[[20,&quot;Load Balance\n&quot;]],&quot;33:0&quot;],&quot;C16&quot;:[40,[[20,&quot;Nginx&quot;,&quot;7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D16&quot;:[40,[[20,&quot;1.16.1&quot;,&quot;7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;A17&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B17&quot;:[40,[[20,&quot;Project build and Management Tools\n&quot;]],&quot;33:0&quot;],&quot;C17&quot;:[40,[[20,&quot;Maven&quot;,&quot;7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D17&quot;:[40,[[20,&quot;3.0+&quot;,&quot;7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;A18&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B18&quot;:[40,[[20,&quot;Distributed locks\n&quot;]],&quot;33:0&quot;],&quot;C18&quot;:[40,[[20,&quot;Tentative DB implementation\n&quot;]],&quot;33:0&quot;],&quot;D18&quot;:[40,[[20,&quot;&nbsp;&quot;,&quot;7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;A19&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B19&quot;:[40,[[20,&quot;Unified Distributed cache\n&quot;]],&quot;33:0&quot;],&quot;C19&quot;:[40,[[20,&quot;Research when needed\n&quot;]],&quot;33:0&quot;],&quot;D19&quot;:[40,[[20,&quot;Not involved yet\n&quot;]],&quot;33:0&quot;],&quot;A20&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B20&quot;:[40,[[20,&quot;Unified log collection and storage\n&quot;]],&quot;33:0&quot;],&quot;C20&quot;:[40,[[20,&quot;Tentative ELK\n&quot;]],&quot;33:0&quot;],&quot;D20&quot;:[40,[[20,&quot;Under planning\n&quot;]],&quot;33:0&quot;],&quot;A21&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B21&quot;:[40,[[20,&quot;Message queue\n&quot;]],&quot;33:0&quot;],&quot;C21&quot;:[40,[[20,&quot;Research when needed\n&quot;]],&quot;33:0&quot;],&quot;D21&quot;:[40,[[20,&quot;Not involved yet\n&quot;]],&quot;33:0&quot;],&quot;A22&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B22&quot;:[40,[[20,&quot;distributed transaction\n&quot;]],&quot;33:0&quot;],&quot;C22&quot;:[40,[[20,&quot;Research when needed\n&quot;]],&quot;33:0&quot;],&quot;D22&quot;:[40,[[20,&quot;Not involved yet\n&quot;]],&quot;33:0&quot;],&quot;A23&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B23&quot;:[40,[[20,&quot;Log printing\n&quot;]],&quot;33:0&quot;],&quot;C23&quot;:[40,[[20,&quot;Log4j2 + self4j&quot;,&quot;7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D23&quot;:[40,[[20,&quot;2.17.1&quot;,&quot;7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;A24&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B24&quot;:[40,[[20,&quot;Front end frame\n&quot;]],&quot;33:0&quot;],&quot;C24&quot;:[40,[[20,&quot;TypeScriptis&quot;,&quot;7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;],&quot;D24&quot;:[40,[[20,&quot;3.5.3&quot;,&quot;7:3&quot;],[20,&quot;\n&quot;]],&quot;33:0&quot;]},[[10,10,&quot;4:22&quot;],[10,1,&quot;4:36&quot;],[10,5,&quot;4:22&quot;],[10,1,&quot;4:38&quot;],[10,2,&quot;4:22&quot;],[10,1,&quot;4:38&quot;],[10,4,&quot;4:22&quot;]],[[10,1,&quot;3:132&quot;],[10,1,&quot;3:142&quot;],[10,1,&quot;3:162&quot;],[10,1,&quot;3:178&quot;]]],&quot;25:\&quot;HJqxYO\&quot;&quot;]]">

DataSphereStudio | category | lectotype | version
-- | -- | -- | --
Microservices module | Microservices governance | Spring Cloud | Finchley.RELEASE
Service Registration and Discovery | Nacos | Not involved yet
Unified Configuration Center | Managis | 1.3.5
Gateway Routing | Spring Cloud Gateway | 2.0.1.RELEASE
service call | OpenFeign | 2.0.0.RELEASE
Service Security Certification | UC | Under planning
Interface Document Engine | GITBOOK(Swagger) | Not involved yet
Service application monitoring | Spring Cloud Admin | Not involved yet
Service Link Tracking | Skywalking | Under planning
The service is degraded, fused, or restricted | Organize and compare Sentinel/Hystrix | Under planning
Load balancing between services | Spring Cloud ribbon | 2.0.0.RELEASE
Basic universal module | database | Mysql | 5.1.34(Driver version)
Data access persistence | Mybatis | 3.4.6
MVC | Spring mvc | 1.19.1
Load Balance | Nginx | 1.16.1
Project build and Management Tools | Maven | 3.0+
Distributed locks | Tentative DB implementation |  
Unified Distributed cache | Research when needed | Not involved yet
Unified log collection and storage | Tentative ELK | Under planning
Message queue | Research when needed | Not involved yet
distributed transaction | Research when needed | Not involved yet
Log printing | Log4j2 + self4j | 2.17.1
Front end frame | TypeScriptis | 3.5.3

</span>
</body>
</html>

1.2 Business architecture
<html>
<body>
<span data-shimo-docs="[[30,[{&quot;A1&quot;:[40,[[20,&quot;组件英文名&quot;,&quot;0:\&quot;%23ffffff\&quot;|27:\&quot;12\&quot;|31:2|7:1&quot;],[20,&quot;\n&quot;]],&quot;1:\&quot;%234472c4\&quot;&quot;],&quot;B1&quot;:[40,[[20,&quot;一级模块&quot;,&quot;0:\&quot;%23ffffff\&quot;|27:\&quot;12\&quot;|31:2|7:1&quot;],[20,&quot;\n&quot;]],&quot;1:\&quot;%234472c4\&quot;&quot;],&quot;C1&quot;:[40,[[20,&quot;二级模块&quot;,&quot;0:\&quot;%23ffffff\&quot;|27:\&quot;12\&quot;|31:2|7:1&quot;],[20,&quot;\n&quot;]],&quot;1:\&quot;%234472c4\&quot;&quot;],&quot;D1&quot;:[40,[[20,&quot;功能点&quot;,&quot;0:\&quot;%23ffffff\&quot;|27:\&quot;12\&quot;|31:2|7:1&quot;],[20,&quot;\n&quot;]],&quot;1:\&quot;%234472c4\&quot;&quot;],&quot;A2&quot;:[40,[[20,&quot;DataSphereStudio&quot;,&quot;27:\&quot;12\&quot;|31:3|7:0&quot;],[20,&quot;\n&quot;]],&quot;5:8|6:1&quot;],&quot;B2&quot;:[40,[[20,&quot;dss-apps-server\n&quot;]],&quot;5:4|6:1&quot;],&quot;C2&quot;:[40,[[20,&quot;dss-scriptis-server\n&quot;]]],&quot;D2&quot;:[40,[[20,&quot;将独立的二级服务模块scriptis、user-guide、apiservice、datapipe统一合并至dss-apps-server服务\n&quot;]],&quot;5:4|6:1&quot;],&quot;A3&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B3&quot;:[40,[[20,&quot;\n&quot;]]],&quot;C3&quot;:[40,[[20,&quot;dss-user-guide-server\n&quot;]]],&quot;D3&quot;:[40,[[20,&quot;\n&quot;]]],&quot;A4&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B4&quot;:[40,[[20,&quot;\n&quot;]]],&quot;C4&quot;:[40,[[20,&quot;dss-apiservice-server\n&quot;]]],&quot;D4&quot;:[40,[[20,&quot;\n&quot;]]],&quot;A5&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B5&quot;:[40,[[20,&quot;\n&quot;]]],&quot;C5&quot;:[40,[[20,&quot;dss-datapipe-server\n&quot;]]],&quot;D5&quot;:[40,[[20,&quot;\n&quot;]]],&quot;A6&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B6&quot;:[40,[[20,&quot;dss-server\n&quot;]],&quot;5:4|6:1&quot;],&quot;C6&quot;:[40,[[20,&quot;dss-framework-project-server\n&quot;]]],&quot;D6&quot;:[40,[[20,&quot;将project-server、orchestrator-server、workflow-server和flow-execution合并至dss-server服务\n&quot;]],&quot;5:4|6:1&quot;],&quot;A7&quot;:[40,[[20,&quot;\n&quot;]],&quot;6:1&quot;],&quot;B7&quot;:[40,[[20,&quot;\n&quot;]],&quot;6:1&quot;],&quot;C7&quot;:[40,[[20,&quot;dss-framework-orchestrator-server\n&quot;]]],&quot;D7&quot;:[40,[[20,&quot;\n&quot;]]],&quot;A8&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B8&quot;:[40,[[20,&quot;\n&quot;]]],&quot;C8&quot;:[40,[[20,&quot;dss-workflow-server\n&quot;]]],&quot;D8&quot;:[40,[[20,&quot;\n&quot;]]],&quot;A9&quot;:[40,[[20,&quot;\n&quot;]]],&quot;B9&quot;:[40,[[20,&quot;\n&quot;]]],&quot;C9&quot;:[40,[[20,&quot;dss-flow-execution-server\n&quot;]]],&quot;D9&quot;:[40,[[20,&quot;\n&quot;]]]},[[10,2,&quot;4:24&quot;],[10,1,&quot;4:31&quot;],[10,6,&quot;4:24&quot;]],[[10,1,&quot;3:135&quot;],[10,1,&quot;3:131&quot;],[10,1,&quot;3:186&quot;],[10,1,&quot;3:162&quot;]]],&quot;25:\&quot;QhD9DC\&quot;&quot;]]">

Component name | First-level module | Secondary module | Function point
-- | -- | -- | --
DataSphereStudio | dss-apps-server | dss-scriptis-server | Merge independent second-level service modules scriptis, user-guide, apiservice and datapipe into dss-apps-server service
dss-user-guide-server
dss-apiservice-server
dss-datapipe-server
dss-server | dss-framework-project-server | Merge project-server, orchestrator-server, workflow-server, and flow-execution into dss-server services
dss-framework-orchestrator-server
dss-workflow-server
dss-flow-execution-server

</span>
</body>
</html>

**2. Module design**

2.1 dss-apps-server service Merging

2.1.1 Adding Submodules
Create a dss-apps-server submodule under the dss-apps module, and create a startup class DSSAppsServerApplication, which is used to merge the lib dependent output directory of other dss-apps submodules.

2.1.2 Modifying pom Dependency
Relying on the dss-scriptis-server,dss-user-guide-server,dss-apiservice-server,dss-datapipe-server module in the pom.xml of dss-apps-server, Other submodules are relied upon to generate the final lib directory. 

2.1.3 Assembly modification
Modify assembly/distribution.xml in dss-package and add a fileSet for dss-app-server to output the dss-apps-server/lib/directory to $DSS_ HOME/lib/dss-apps-server/. And retain the output directory of the original service to preserve the old service startup method.

2.1.4 Configuration File Update
Add the dss-apps-server.properties configuration file and merge the configuration file items of scriptis, guide, apiservice, and datapipe into dss-apps-server.properties. Among them, the configuration items wds. linkis.server.mybatis.* and wds.linkis.server.restful. * need to merge the corresponding configuration items of each service in a comma separated manner, and the other non conflicting configuration items can be directly copied to the new configuration file. And keep the old configuration files for scriptis, guide, apiservice, and datapipe to be compatible with the old service startup method. By default, the dss.properties and newly added dss-app-server.properties configurations are read. If there are any new configuration files, read the new configuration files first. If there are no new configuration files, load the previous configuration files.
![服务合并-配置文件](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/0ac32681-9ebd-4f0d-86c9-83234f0c8422)

2.1.5 gateway Forwarding Modification
Modify the url forwarding logic of dss-gateway-support to forward interfaces of apiservice, datapipe, scriptis, and guideserver to dss-app-server.
The matching logic between the requested url and the service is as follows: The url is divided into substrings based on slashes /. If a service name contains the most substrings, the service is selected to forward the corresponding url. If the matching times are the same, the service name with the shortest length is selected. Before entering the matching rule, prefix the interfaces of these templates with a section /apps to match the dss-apps-server service. In order to be compatible with the old service startup mode, configure items to control whether to use the new forwarding logic.
![服务合并-gateway转发](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/7d7cd11c-021f-4e28-9294-d67d028d0753)

2.1.6 Script Update
The corresponding scripts of scriptis, guide, apiservice, and datapipe are reserved in the sbin/ext directory, and the dss-apps-server scriptis added. Add new dss-start-all_new.sh and dss-stop-all_new.sh scripts, and add related commands for starting and stopping dss-apps-server.
The assembly/config/config. Sh script, add apps-server IP and PORT configuration items, and keep the scriptis, guide, apiservice, datapipe service corresponding to the IP and PORT configuration items, to compatible with the old way.
The install and update scripts create two new templates based on the existing templates to adapt to the new deployment structure and retain the original templates.
A version of an old script is reserved for rollback.

2.1.7 Update the managis component template
Keep scriptis, guide, apiservice, datapipe service templates and configuration templates of DSS1.0 components, and add service templates and configuration templates of dss-apps-server.
A version of an old template is reserved for rollback.

2.1.8 Upgrading the Cluster Environment
When upgrading the cluster environment, you need to associate the services and configurations of dss-apps-server. Retain service and configuration for scriptis, guide, apiservice, datapipe. One version of the old service configuration is reserved for rollback.
![服务合并-合并前后](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/2854eb44-3223-4362-b036-31c4de67cc97)

**2.2 Merging dss-server Services**

2.2.1 Creating a Submodule
Create a new dss-server root module and create the startup class DSSServerApplication.

2.2.2 Modifying pom Dependency
It relies on dss-framework-project-server,dss-framework-orchestrator-server,dss-workflow-server,dss-flow-execut in the pom.xml of dss-server, adding dependencies to generate the final lib directory.

2.2.3 Assembly modification
Modify the assembly/distribution.xml in dss-package and add the fileSet of dss-server to output the dss-server/lib/directory to $DSS_ HOME/lib/dss-server/. And retain the output directory of the original service to preserve the old service startup method.

2.2.4 Configuration file update
Merge the configuration file items for project-server, orchestrator-server, workflow-server, and flow-execution into a new dss-server. properties. Among them, the configuration items wds.linkis.server.mybatis.* and wds.linkis.server.restful.* need to merge the corresponding configuration items of each service in a comma separated manner, and the other non conflicting configuration items can be directly copied to the new configuration file. By default, read the configuration of dss.properties and corresponding service dss-server.properties. If there are new dss-server.properties configuration files, read the new configuration files first. If there are no new configuration files, load the previous configuration files.

2.2.5 rpc Call Modification
The remote rpc call is changed to the local rpc call and compatible with the old service startup method.
Implement a new dss-server-sender and add a configuration item isMergeService to control whether to forward the sender from project, orchestrator, and workflow to dss-server-sender. If you check in getProjectServerSender that if the configuration item is enabled, the ds-server-sender is returned. If the startup mode of service merger is adopted, you need to enable this configuration item to forward the sender of each service to the dss-server-sender, which is equivalent to the local rpc invocation. If the old service start mode is used separately, disable this configuration item and use the original remote rpc invocation mode. Implement the new senderService and change the factory to the new one.
rpc call from orchestrator-server to workflow-server before service merging:
![服务合并-rpc调用前](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/f29c41e8-9b3a-427c-bc93-b8dfa4d34df6)
rpc call from orchestrator-server to workflow-server after service merger:
![服务合并-rpc调用-后](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/18e0a8e9-07f7-4a15-8b69-f55568e781c1)

2.2.6 Conflict handling of beans with the same name
Integrate all modules' BmlService classes into the dss-commons package to provide a unified bmlService utility class. Remove the BmlService classes of project-server, orchestrator-server, and workflow-server, and introduce the bmlservice of the dss-commons module into the user side. To register as a bean through the @bean annotation of springconf, you need to register your own bean in project, orchestrator, and workflow with a unique name because you want to be compatible with the two startup methods of service merging and separation.
MetaExportService and MetaImportService in orchestrator and workflow-server need to register and use their own beans in orchestrator and workflow-server, and their names must be unique.

2.2.7 rpc Compatible at release time

2.2.8 Compatible with AppconnManagerClient

2.2.9 Script Update
Add the dss-apps-server script in the sbin/ext directory. dss-start-all_new.sh and dss-stop-all_new.sh scripts were added, and related commands for starting and stopping dss-server were added. One version of the old start_all and stop_all scripts is reserved for rollback.
Add the IP and PORT configuration items for dss-server to the assembly/config/config.sh script.
The install and update scripts create two new templates based on the existing templates to adapt to the new deployment structure and retain the original templates.
An old script version is reserved for rollback.

2.2.10 managis Component Template
Add the dss-server service configuration and template. And retain the original service templates.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.2
