### ISSUE TITLE
[Feature] Spark task configuration defaults to removing units

### ISSUE THREAD

**Issue by wxyn** [WeBankFinTech/DataSphereStudio#1097]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

In the current Spark node configuration, units are added by default, such as G | g. Due to previous modifications on Linkis, unit restrictions were uniformly added at the beginning of 1.0.

### Description

1. Unify the node configuration with the management console. By default, the unit G | g is removed and expressed in numbers.
2. Display location
![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/46619096/70618551-93a7-433e-8aae-1cbb2815ac40)

3. To support historical tasks, already configured users have stored units.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Addi it in DSS1.1.2
