### ISSUE TITLE
添加流程时提示首次上传资源失败

### ISSUE THREAD

**Issue by fasoal** [WeBankFinTech/DataSphereStudio#110]
版本:0.7.0
操作:创建工作流
接口:addFlow
message: "operation failed(操作失败)s！the reason(原因)：HttpClientResultException: errCode: 10905 ,desc: URL http://127.0.0.1:9901/api/rest_j/v1/bml/upload request failed! ResponseBody is {"method":null,"status":1,"message":"error code(错误码): 60050, error message(错误信息): 首次上传资源失败.","data":{"errorMsg":{"serviceKind":"bml-server","level":2,"port":9113,"errCode":50073,"ip":"bdc-hadoop-test-10-61","desc":"提交上传资源任务失败:errCode: 60050 ,desc: 首次上传资源失败 ,ip: bdc-hadoop-test-10-61 ,port: 9113 ,serviceKind: bml-server"}}}. ,ip: bdc-hadoop-test-10-61 ,port: 9004 ,serviceKind: dss-server"
![image](https://user-images.githubusercontent.com/14243815/75415388-71dbfc00-5966-11ea-9485-814dd369bec2.png)
![image](https://user-images.githubusercontent.com/14243815/75415401-7c969100-5966-11ea-9b76-bc20789bf795.png)

**Comment by peacewong** [comment]
https://github.com/WeBankFinTech/DataSphereStudio/wiki/FAQ_for_Usage
Hello, you can check the question 5
