### ISSUE TITLE
安装精简版需要先安装好hadoop吗

### ISSUE THREAD

**Issue by dddengyunjie** [WeBankFinTech/DataSphereStudio#121]
安装精简版时，执行安装脚本时报错bin/install.sh:行249: hdfs: 未找到命令
我的系统是没有安装hadoop的，看文档里并没要求安装啊

**Comment by dddengyunjie** [comment]
RESULT_SET_ROOT_PATH=hdfs:///tmp/linkis  # 结果集文件路径，用于存储Job的结果集文件

**Comment by dddengyunjie** [comment]
配置文件里需要把RESULT_SET_ROOT_PATH=hdfs:///tmp/linkis # 结果集文件路径，用于存储Job的结果集文件
这行注释了才能正常安装

**Comment by chaogefeng** [comment]
@dddengyunjie If you need to use hdfs to store the result set, you need to install hdfs
