### ISSUE TITLE
工作流创建失败后，记录依旧保存在dss_flow表中，无法再次创建同名的工作流

### ISSUE THREAD

**Issue by renrr** [WeBankFinTech/DataSphereStudio#122]
当在创建工作流时，出现了No FileSystem for scheme \"hdfs\".","data":{"errorMsg":{"serviceKind":"bml-server","level":2,"port":9113,"errCode":50073,"ip":"linux46","desc":"提交上传资源任务失败:No FileSystem for scheme \"hdfs\""}}}. ,ip: linux46 ,port: 9004 ,serviceKind: dss-server
导致工作流创建失败，再次创建该工作流，提示无法创建同名的工作流

**Comment by jhj-123** [comment]
这个是可以在表中手动删除的。
