### ISSUE TITLE
Azkaban 调度hql 任务失败

### ISSUE THREAD

**Issue by jkl0898** [WeBankFinTech/DataSphereStudio#130]
版本：
wedatasphere-dss-0.7.0
wedatasphere-linkis-0.9.3

azkaban 为一键部署生成

现象：运行azkaban 报相关jackson 类找不到， 如下图：
![image](https://user-images.githubusercontent.com/14175165/79738925-0728ba80-8330-11ea-92eb-7f9029615eee.png)

定位原因：
azkaban/lib 下有jackson-core-2.2.2.jar ， plugins 目录下的版本为 plugins/jobtypes/linkis/lib/jackson-core-2.9.6.jar 。 两者冲突。

解决建议：
统一jar 包的版本， 如将azkaban/lib 更新为jackson-core-2.9.6.jar。

目前通过更新azkaban/lib  包为jackson-core-2.9.6.jar 任务运行成功。

**Comment by yangzhiyue** [comment]
There are some low-version jars in  Azkaban , But it will be excluded in Schedulis of WeDataSphere,
I strongly recommend that you use Schedulis 
https://github.com/WeBankFinTech/Schedulis
