### ISSUE TITLE
scala 类型 UDF 前端 BUG

### ISSUE THREAD

**Issue by wForget** [WeBankFinTech/DataSphereStudio#131]
1. scala 参数类型应该允许为空
2. scala useFormat 保存有问题
3. 返回或参数类型为复合类型的时候有问题（']'的判断）
![image](https://user-images.githubusercontent.com/17894939/79743180-ba94ad80-8336-11ea-97dd-c8102af32a82.png)
![image](https://user-images.githubusercontent.com/17894939/79743215-c84a3300-8336-11ea-9bac-ee9cb1113dd3.png)

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
持续为DataSphereStudio开源贡献力量
