### ISSUE TITLE
该项目还继续维护吗

### ISSUE THREAD

**Issue by cmdares** [WeBankFinTech/DataSphereStudio#137]
目前发现该项目已经有3个月没有更新了，请问官方项目的进度情况，后续什么时候发布新版本，有无长期的roadmap？

**Comment by wushengyeyouya** [comment]
Hello, we are preparing a large version recently, so it will take more time and it is expected to be officially released this month, so stay tuned!
DataSphere Studio is positioned as a one-stop data application development and management portal, and will continuously improve the development and management functions of data applications to achieve the ecological closed loop of big data development.

**Comment by yangzhiyue** [comment]
你好，dss项目当然还在维护当中，现在还正在规划更多、更新的功能，dss也有清晰的roadmap，您可以关注我们的公众号，或者加入我们的微信或者qq交流群进行交流
-----------------
Hello, DSS is definitely active now, We are planning some stronger and brand new features and dss has a very clear roadmap. You can follow our  public account in wechat and join wechat group or qq
group to communicate with us

**Comment by jacksu** [comment]
大版本什么时候发布呢？

**Comment by wushengyeyouya** [comment]
We expect to release the official version of DSS1.0.0 in July. Before that, we will release DSS0.8.0 next week, so stay tuned!
