### ISSUE TITLE
visualis创建view时执行hql无查询结果

### ISSUE THREAD

**Issue by hankai520** [WeBankFinTech/DataSphereStudio#145]
操作步骤：
1. 在hive中创建库表
2. hive 表中load数据
3. hive命令行测试查询数据
4. 进入 visualis，创建view，填写hql：select * from stat_by_industry; 执行无结果

创建view界面左侧数据源菜单可以正常加载库表信息。

日志：
2020-06-09 17:07:02,190 INFO  (qtp1527597068-26) INFO DefaultResultSetFactory - Wrong result Set: File header type must be dolphin,content:hdfs:///tmp/linkis/hadoop/dwc/20200609/Visualis/1707/_0.dolphin is not

附件为 /tmp/linkis/hadoop/dwc/20200609/Visualis/1707/_0.dolphin 文件。

[_0.dolphin.zip](https://github.com/WeBankFinTech/DataSphereStudio/files/4751124/_0.dolphin.zip)

**Comment by peacewong** [comment]
Hello, did visualis report an error?The above is not an error message.

**Comment by hankai520** [comment]
界面没有错误，附件添加了前端ajax请求、响应。hive命令行可以查询到数据。
![Screen Shot 2020-06-10 at 8 53 54 AM](https://user-images.githubusercontent.com/5268336/84215176-0faf9d00-aaf8-11ea-9ef0-bda9e838b6dc.png)
![Screen Shot 2020-06-10 at 8 54 10 AM](https://user-images.githubusercontent.com/5268336/84215182-14745100-aaf8-11ea-92f5-89c26c3a50d3.png)

**Comment by hankai520** [comment]
可能和hql写法有关系，“改成 select * from 库名.表名” 这种形式就可以了。
