### ISSUE TITLE
visualis预览问题（中文乱码）

### ISSUE THREAD

**Issue by hankai520** [WeBankFinTech/DataSphereStudio#146]
使用dss全家桶，绘制好visualis display之后，点击预览，渲染不出界面，日志提示 phantomjs 执行失败（见附件）。去官网下载phantomjs二进制文件并替换原文件后，再预览还是不出界面，日志提示缺少libfontconfig.so，执行 “yum install fontconfig freetype freetype-devel fontconfig-devel libstdc++”，再预览，可以看到界面，但是界面中文无法显示（见附件
![phantomjs问题日志](https://user-images.githubusercontent.com/5268336/84233409-de999180-ab24-11ea-992b-12e05629b2ce.png)
![visualis中文乱码](https://user-images.githubusercontent.com/5268336/84233431-e8bb9000-ab24-11ea-809a-982d8035bbe7.png)

）。

**Comment by hankai520** [comment]
补充一下，预览生成的截图有中文乱码，但是分享的链接访问没有乱码。猜测是截图那块底层有问题。

**Comment by MountHuang** [comment]
需要在Linux机器上安装中文字体，比如宋体之类的。具体步骤：
1. 拷贝ttf文件到/usr/share/fonts/
2. 执行fc-cache -fv
2. 用fc-list确认字体是否安装成功
