### ISSUE TITLE
DSS-0.9.0 community communication

### ISSUE THREAD

**Issue by Adamyuanyuan** [WeBankFinTech/DataSphereStudio#154]
DSS0.9.0 is an important version completed by Ctyun with the help of Webank.
This version aims to build  **a one-stop big data development and service platform**  by introducing the concepts of  "**DSS Integration Standard**"  and "**workspace**", and greatly improve user's experience of big data development.
## Introduction to the concept:
**DSS Integration Standard** : The unified access specification for application system composed of SecurityService is extracted from the AppJoint specification of DSS, so that enterprises can easily connect relevant big data products to DSS and quickly acquire the capability of one-stop big data application store.
**Workspace** : Enables different types of data applications (such as: offline workflow application, real-time application, data API service, etc.) to be organized and managed from a unified perspective to improve application development and management specifications;
## The specific development content is as follows:

- Home page reconstruction, create workspace, case experience area, quick start and other areas, to provide new users with better use guidance;
- New workspace page, in which users can conduct all kinds of big data development projects in a one-stop manner:
    • Common function sub-module, users can customize common functions for easy access;
    • Application store sub-module, users can easily browse and search all big data-related development tools;
    • Administrator function sub-module, the workspace administrator can set and manage the workspace;
- And some known bug fixes;
----
# DSS-0.9.0版本社区交流
DSS0.9.0版本是在微众银行的倾力帮助下，由天翼云主导完成的一个重要版本。
该版本旨在通过引入“**DSS应用接入规范**”，“**工作空间**”等概念，构建**一站式大数据开发与服务平台**，极大提升用户大数据开发的体验，其中：

## 概念简介：
**DSS应用接入规范：** 是从DSS的AppJoint规范中，抽出SecurityService组成的应用系统统一接入规范，使企业可以非常简单地将相关大数据产品接入到DSS之中，快速具备一站式的大数据应用系统门户展示和管理能力（DSS应用接入规范将会在DSS的后续版本之中继续补充完善）。
**工作空间规范：** 使不同类型的数据应用（如：工作流离线应用、实时应用、数据API服务等）能够以统一的视角进行组织管理，提升应用的开发和管理规范；

## 具体开发内容如下：
• 首页重构，新增工作空间功能、案例体验区、快速入门等区域，为新手用户提供更好的使用指导；
• 新增工作空间页面，在工作空间内，用户可以一站式地进行各类大数据开发项目：
    • 常用功能子模块，用户可以自定义常用功能以方便地进入；
    • 应用商店子模块，用户可以方便地浏览，搜索所有的大数据相关开发工具；
    • 管理员功能子模块，工作空间管理员可以对工作空间进行设置与管理；
• 以及一些已知bug的修复；

**Comment by wushengyeyouya** [comment]
Thanks to the participation and contribution of the Ctyun big data team, This release brings the concepts of "one-stop" and "workspace" to the DataSphere Studio community, and it is very significant to improve the user's big data development and management experience. It is an important version of DataSphere Studio. Looking forward to the grand release of DataSphere Studio Release-0.9.0!

---

感谢天翼云大数据团队的倾情参与和贡献，为DataSphere Studio社区带来了“一站式”和“工作空间”等概念，非常显著地提升了用户的大数据开发管理体验，是DataSphere Studio承前启后的一个重要版本，非常期待DataSphere Studio Release-0.9.0的重磅发布！

**Comment by Vinsmoke66** [comment]
希望能整合Exchangis

**Comment by Adamyuanyuan** [comment]
> 希望能整合Exchangis

这一块跟linkis有关，快了

**Comment by yuchenyao** [comment]
Looking forward to the new release of DSS

**Comment by det101** [comment]
Expect more features

**Comment by 77954309** [comment]
> > 希望能整合Exchangis
> 
> 这一块跟linkis有关，快了

这个Exchangis前端什么时候开放出来，我这边做Exchangis一直都用Beam做，后续有想法整合在一起

**Comment by Adamyuanyuan** [comment]
> > > 希望能整合Exchangis
> > 
> > 
> > 这一块跟linkis有关，快了
> 
> 这个Exchangis前端什么时候开放出来，我这边做Exchangis一直都用Beam做，后续有想法整合在一起

@wushengyeyouya 我觉得很好啊。我们这边特殊场景的接入是用spark-streaming比较定制化的，怎么整合是个问题

**Comment by wushengyeyouya** [comment]
Thanks to the contribution of Ctyun, this version was already been published successfully, now close this issue.
