### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.3.0:single (make-assembly) on project dss-server: Assembly is incorrectly configured: dss-server

### ISSUE THREAD

**Issue by LawrenceKyle** [WeBankFinTech/DataSphereStudio#222]
I tried to compile DSS manually，but it occur this error midway . I `ve tried change the maven-assembly-plugin`s version 2.3 to 3.3.0. This error tips has still happened.Here is my error picture about this error. so sorry about my english level.
![TIM截图20200724111129](https://user-images.githubusercontent.com/53593337/88357598-759d6e80-cd9e-11ea-9964-04d25320bdbb.png)

**Comment by xujie3930** [comment]
![image](https://user-images.githubusercontent.com/86453259/127625111-59125c52-6777-4464-ae06-918921dd0812.png)
Try this
