### ISSUE TITLE
怎么会有两份文档

### ISSUE THREAD

**Issue by zhouyf14** [WeBankFinTech/DataSphereStudio#239]
https://github.com/WeBankFinTech/DataSphereStudio/blob/master/docs/zh_CN/ch2/DSS_LINKIS_Quick_Install.md

https://github.com/WeBankFinTech/DataSphereStudio/blob/master/docs/zh_CN/ch2/DSS%E5%BF%AB%E9%80%9F%E5%AE%89%E8%A3%85%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3.md#%E4%BA%8C%E7%B2%BE%E7%AE%80%E7%89%88dss%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE%E5%87%86%E5%A4%87

**Comment by wushengyeyouya** [comment]
One is the one-click installation and deployment document of WeDataSphere Family Bucket, and the other is the installation and deployment document of only DSS
