### ISSUE TITLE
Airflow Integration

### ISSUE THREAD

**Issue by yangrong688** [WeBankFinTech/DataSphereStudio#242]
Does DataSphereStudio support Airflow Integration? 
If so, is there some guide to reference.

**Comment by geosmart** [comment]
the nio impl airflow integrated with dss by
[241](https://github.com/WeBankFinTech/DataSphereStudio/pull/241/files),

you can find the detail in [DSS在蔚来汽车的实践](https://github.com/WeBankFinTech/WeDataSphere/issues/26)
