### ISSUE TITLE
数据可视化页面打开异常（visualis_nginx_ip_2）

### ISSUE THREAD

**Issue by yipwinghong** [WeBankFinTech/DataSphereStudio#243]
从主页打开“数据可视化”页面提示有报错，打开调试工具可见接口请求的地址为 http://visualis_nginx_ip_2:8088/api/rest_s/v1/visualis/projects，请问 ip 地址应该在哪里配置呢？
（同理还有打开“数据质量”页提示“qualitis_adress_ip_2’s server IP address could not be found.”）

恳请解答，谢谢。

**Comment by Tandoy** [comment]
How did you solve it

**Comment by iwasjoker** [comment]
你好，这个问题怎么解决的
