### ISSUE TITLE
release 090 compile error 

### ISSUE THREAD

**Issue by yonger1516** [WeBankFinTech/DataSphereStudio#276]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.3:single (make-assembly) on project dss-server: Assembly is incorrectly configured: dss-server: Assembly is incorrectly configured: dss-server:
[ERROR] Assembly: dss-server is not configured correctly: One or more filters had unmatched criteria. Check debug log for more information.
[ERROR] -> [Help 1]

**Comment by peacewong** [comment]
Hello, you can check FAQ 7：https://github.com/WeBankFinTech/Linkis/wiki/Q&A-%E9%97%AE%E9%A2%98%E6%80%BB%E7%BB%93
