### ISSUE TITLE
wrong user name or password

### ISSUE THREAD

**Issue by peniridis** [WeBankFinTech/DataSphereStudio#30]
![image](https://user-images.githubusercontent.com/11739301/70709244-68ec6e80-1d17-11ea-9f8a-7fbcd92f16ec.png)
i follow the Installation guide but 
![image](https://user-images.githubusercontent.com/11739301/70709477-ed3ef180-1d17-11ea-9829-22709ecf5f78.png)
there no user in the linkis or dss database and 
```
linkis-gateway error logs

2019-12-12 19:13:54.007 WARN  [reactor-http-nio-3]
com.webank.wedatasphere.linkis.gateway.security.LDAPUserRestful 55 warn - 
wrong user name or password
javax.naming.ConfigurationException: 
java.naming.provider.url property does not contain a URL
```
help！thanks

**Comment by wushengyeyouya** [comment]
Please add LDAP information.

**Comment by peniridis** [comment]
it works so it's required configuration 
## LDAP is for enterprise authorization, if you just want to have a try, ignore it.
#LDAP_URL=ldap://localhost:1389/
#LDAP_BASEDN=dc=webank,dc=com

**Comment by yanbo5257** [comment]
我遇到了同样的问题
