### ISSUE TITLE
编译DSS1.0.0-dev编译不通过

### ISSUE THREAD

**Issue by KabourWu** [WeBankFinTech/DataSphereStudio#402]
DSS1.0.0-dev 源码linkis-jobtype模块依赖
<dependency>
 <groupId>com.webank.wedatasphere.schedulis</groupId>
<artifactId>azkaban-common</artifactId>
<version>0.6.1</version>
</dependency>
schedulis项目源码只有0.6.0版本，没有0.6.1版本。尝试依赖0.6.0的包，发现版本不兼容。

**Comment by wushengyeyouya** [comment]
This problem has resolved.
