### ISSUE TITLE
schedulis:pom:0.6.1 could not find

### ISSUE THREAD

**Issue by jackxu2011** [WeBankFinTech/DataSphereStudio#416]
maven clean package
Could not find artifact com.webank.wedatasphere.schedulis:schedulis:pom:0.6.1

the artifact com.webank.wedatasphere.schedulis:azkaban-common:pom:0.6.1 's parent

**Comment by sysuzhang** [comment]
i have meet the same error

**Comment by sysuzhang** [comment]
I fix this error， we need to install the dependency first：
1. navigate to https://github.com/WeBankFinTech/Schedulis/releases/tag/release-0.6.1
2. Down load the Schedulis-release-0.6.1.tar.gz 
3. build and install the Schedulis-0.6.1 by mvn install
4. return to the DataSphereStudio project and retry, finally I got success.

**Comment by jackxu2011** [comment]
i just want the artifact com.webank.wedatasphere.schedulis:schedulis:pom:0.6.1 can be push to maven center.  reduce the time for the new user
