### ISSUE TITLE
How does dss integrate with azkaban？

### ISSUE THREAD

**Issue by yangjiajun2014** [WeBankFinTech/DataSphereStudio#42]
Hello,DSS community.I would like to know:

How does work flow of dss translate to azkaban's runtime?

How does azkaban communicate with dss?

I am reading the code but still confused.Very appreciated it if you could give me some hints.

**Comment by wushengyeyouya** [comment]
DSS will interact with Azkaban in the following situations:
1. Login. Please refer to: AzkabanSecurityService
2. Create / delete / update project, Azkaban will also perform the same operation simultaneously. Please refer to: AzkabanProjectService
3. Publish a project. DSS will convert a DSS project into a project that can be loaded by Azkaban by parsing-> tuning-> Hook-> publish, and then call Azkaban's publishing restful API to publish project. Please refer to: dss-azkaban-scheduler-appjoint and dss-scheduler-appjoint-core modules.

dss-scheduler-appjoint-core is an abstract general publish module about parsing-> tuning-> Hook-> publish , and dss-azkaban-scheduler-appjoint is a implement based on dss-scheduler-appjoint-core.

Welcome to implement a new scheduler AppJoint based on dss-scheduler-appjoint-core.

**Comment by yangjiajun2014** [comment]
#77

**Comment by yangjiajun2014** [comment]
Thx.
