### ISSUE TITLE
DSS-Linkis全家桶20210831

### ISSUE THREAD

**Issue by dongjycode** [WeBankFinTech/DataSphereStudio#443]
问题描述：
    Hello,当我一键部署完成并启动后，访问页面出现接口异常的情况，打开浏览器控制台后发现，接口出现404的的问题
![image](https://user-images.githubusercontent.com/91414395/140483567-7e0e97a0-cf22-43ac-8971-59a70fc7e866.png)
Example: 单独调用http://host:port/api/rest_j/v1/dss/framework/接口时也会出现404问题，如果把后缀部分“/framework/”去掉，貌似能调用通，如图：
![image](https://user-images.githubusercontent.com/91414395/140483957-1606b749-e80e-4060-9a87-c1850a4ad511.png)
盼望解答，谢谢！

**Comment by dongjycode** [comment]
自行解决

**Comment by c123853648** [comment]
请问这个问题你是咋解决的啊？

**Comment by qianxiaoning** [comment]
我也遇到这个问题了
