### ISSUE TITLE
dev-1.0.1 ，dss-apiservice-server 编译报错

### ISSUE THREAD

**Issue by seeTheWord** [WeBankFinTech/DataSphereStudio#470]
需要修改：
com.webank.wedatasphere.dss.apiservice.core.service.impl.ApiServiceImpl
注释：49行 //import org.mortbay.log.log;
修改： 247行
 修改前：Log.info("Update to other Api Service, ID: " + apiService.getTargetServiceId() + ",resourceId:" + maxTargetApiVersionVo.getBmlResourceId());

修改后：LOG.info("Update to other Api Service, ID: " + apiService.getTargetServiceId() + ",resourceId:" + maxTargetApiVersionVo.getBmlResourceId());
com.webank.wedatasphere.dss.apiservice.core.token.JwtManager
注释：32行：//import org.mortbay.log.Log;
修改：74行
修改前： Log.info("token key str:"+key.toString());
修改后： LOG.info("token key str:"+key.toString());

**Comment by liuyou2** [comment]
This problem will be solved in the latest version of DSS 1.0.1
