### ISSUE TITLE
希望DSS支撑

### ISSUE THREAD

**Issue by wangjingquang** [WeBankFinTech/DataSphereStudio#48]

**Comment by wangjingquang** [comment]
考虑集成到现有的系统中，历史原因，很多数据处理的脚本都是shell编写的，希望DSS能支撑shell脚本的能力，多谢。

**Comment by wushengyeyouya** [comment]
The reason why the shell engine is not open is that it will cause users to write hive -e or spark -e in the shell code, which will undoubtedly make the management of the entire big data platform more difficult, and many advanced features of DSS and Linkis (such as: resources Management, concurrency restrictions, multi-tenant isolation, etc.) will be ineffective.

**Comment by wangjingquang** [comment]
Ok, I understand.

**Comment by wushengyeyouya** [comment]
So there are three options:
1. Migrate historical data processing scripts to DSS. Of course, this cost is high, but it is very beneficial to the entire platform, and it can also help the business sort out the entire business chain.
2. the incremental business requirements use DSS. Do not migrate the historical data processing scripts.
3. support shell engine and shell workflow node in the future DSS release.

We recommend Option 2 and of course we will seriously consider it if the community partners want to support Option 3.

**Comment by wushengyeyouya** [comment]
Shell engine was supported in DSS 0.7.0, welcome to upgrade and use it.
