### ISSUE TITLE
dss1.0.1 + linkis1.0.3 部署脚本错误，linkis安装失败

### ISSUE THREAD

**Issue by qiaobu** [WeBankFinTech/DataSphereStudio#524]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar issues.

### DSS Component

dss-standard

### What happened + What you expected to happen

You chose not execute table-building statements
create hdfs  directory and local directory
Succeed to + create file:///tmp/linkis/ directory
Succeed to + create hdfs:///tmp/linkis directory
Succeed to + create hdfs:///tmp/linkis directory
create dir LINKIS_HOME: /home/hdfs/DSS-Linkis/linkis-pre-install/LinkisInstall
Succeed to + Create the dir of /home/hdfs/DSS-Linkis/linkis-pre-install/LinkisInstall
Start to cp /home/hdfs/DSS-Linkis/linkis-pre-install/linkis-package to /home/hdfs/DSS-Linkis/linkis-pre-install/LinkisInstall.
Succeed to + cp /home/hdfs/DSS-Linkis/linkis-pre-install/linkis-package to /home/hdfs/DSS-Linkis/linkis-pre-install/LinkisInstall
Update config...
update conf /home/hdfs/DSS-Linkis/linkis-pre-install/LinkisInstall/conf/linkis.properties
update conf /home/hdfs/DSS-Linkis/linkis-pre-install/LinkisInstall/conf/linkis-mg-gateway.properties
update conf /home/hdfs/DSS-Linkis/linkis-pre-install/LinkisInstall/conf/linkis-ps-publicservice.properties
Congratulations! You have installed Linkis 1.0.3 successfully, please use sh /home/hdfs/DSS-Linkis/linkis-pre-install/LinkisInstall/sbin/linkis-start-all.sh to start it!
Your default account password ishdfs/18bdaf152
Succeed to + install Linkis

### Relevent platform

centos7

### deploy user
deployUser=hdfs

HIVE_META_URL=jdbc:mysql://hadoop01:3306/hive?characterEncoding=UTF-8
HIVE_META_USER=hive
HIVE_META_PASSWORD=hive

###HADOOP CONF DIR #/appcom/config/hadoop-config
HADOOP_CONF_DIR=/etc/hadoop/3.1.5.0-152/0/
###HIVE CONF DIR  #/appcom/config/hive-config
HIVE_CONF_DIR=/etc/hive/3.1.5.0-152/0/
###SPARK CONF DIR #/appcom/config/spark-config
SPARK_CONF_DIR=/etc/spark2/3.1.5.0-152/0/

## Engine version conf
#SPARK_VERSION
SPARK_VERSION=2.3.0
##HIVE_VERSION
HIVE_VERSION=3.1.0
#PYTHON_VERSION=python2

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qiaobu** [comment]
一键部署安装脚本有错误，安装完成提示安装成功。安装过程中出现dss-pre-install目录，安装结束linkis目录没有出现，并且dss-pre-install目录也被删除。

**Comment by zhouhongyu888** [comment]
> 一键部署安装脚本有错误，安装完成提示安装成功。安装过程中出现dss-pre-install目录，安装结束linkis目录没有出现，并且dss-pre-install目录也被删除。

是的，遇到一样的问题

**Comment by being23** [comment]
也遇到了这个问题，看起来是 linkis/conf/linkis-env.sh 中的变量 `LINKIS_HOME` 被注释掉了，而在 replace.sh 中定义的`LINKIS_HOME`这个变量不会传递给子进程，导致 linkis 安装脚本中这个变量为空，走了 else 逻辑。使用临时目录作为安装目录，安装结束后，临时目录被删掉了。
