### ISSUE TITLE
[Bug] 【dss1.0.1】版本: 在工作流拖拽了jdbc，双击该jdbc节点，页面无法正常打开

### ISSUE THREAD

**Issue by GodfreyGuo** [WeBankFinTech/DataSphereStudio#549]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar issues.

### DSS Component

dss-web/dss-workflow

### What happened + What you expected to happen

jdbc组件双击后页面无法正常打开，出现以下错误：
![f4e32c20541532236d51d5e6be81b5a](https://user-images.githubusercontent.com/22410655/160062499-0a6dbe16-d460-4aaa-bd74-fb5bc0b68340.png)

需在web代码修改：
// 文件：web/src/apps/workflows/module/process/index.vue
// 27、28行改成：
:class="nodeImg[item.node.type]&&nodeImg[item.node.type].class"
:src="nodeImg[item.node.type]?nodeImg[item.node.type].icon:item.node.image"

// 文件：web/src/apps/workflows/service/nodeType.js
// 58行后面增加jdbc配置（注意上一行最后加逗号）
JDBC: 'linkis.jdbc.jdbc'

// 文件：web/src/common/config/scriptis.js
// 66行后面增加jdbc配置（注意上一行最后加逗号）
[NODETYPE.JDBC]: 'jdbc'

### Relevent platform

linkis 1.0.3
dss 1.0.1

### Reproduction script

none

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by windwhisper-i** [comment]
![image](https://user-images.githubusercontent.com/73170854/161002908-ce8c7dec-d9ce-4117-b045-c822d79fd237.png)

**Comment by wushengyeyouya** [comment]
This bug has fixed.
