### ISSUE TITLE
[Bug] (v1.0.1) {"status":404,"error":"Not Found","message":"","path":"/api/rest_j/v1/dss/framework/workspace/workspaces"}

### ISSUE THREAD

**Issue by gongzh021** [WeBankFinTech/DataSphereStudio#560]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar issues.

### DSS Component

dss-apps/dss-apiservice

### What happened + What you expected to happen

我使用的是全家桶1.0.1版本，一键安装，启动成功，访问登录页面成功，登录成功后跳转到页面，报错接口404，这个bug是我安装的问题，还是软件本身的问题？

{"timestamp":1648986200967,"status":404,"error":"Not Found","message":"","path":"/api/rest_j/v1/dss/framework/workspace/workspaces"}

{"timestamp":1648986200972,"status":404,"error":"Not Found","message":"","path":"/api/rest_j/v1/dss/framework/workspace/workspaces/videos"}

{"timestamp":1648986200995,"status":404,"error":"Not Found","message":"","path":"/api/rest_j/v1/dss/framework/workspace/getBaseInfo"}

{"timestamp":1648986200961,"status":404,"error":"Not Found","message":"","path":"/api/rest_j/v1/dss/framework/workspace/workspaces/departments"}

### Relevent platform

centos7

### Reproduction script

null

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by gongzh021** [comment]
> ### Search before asking
> * [x]  I searched the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar issues.
> 
> ### DSS Component
> dss-apps/dss-apiservice
> 
> ### What happened + What you expected to happen
> 我使用的是全家桶1.0.1版本，一键安装，启动成功，访问登录页面成功，登录成功后跳转到页面，报错接口404，这个bug是我安装的问题，还是软件本身的问题？
> 
> {"timestamp":1648986200967,"status":404,"error":"Not Found","message":"","path":"/api/rest_j/v1/dss/framework/workspace/workspaces"}
> 
> {"timestamp":1648986200972,"status":404,"error":"Not Found","message":"","path":"/api/rest_j/v1/dss/framework/workspace/workspaces/videos"}
> 
> {"timestamp":1648986200995,"status":404,"error":"Not Found","message":"","path":"/api/rest_j/v1/dss/framework/workspace/getBaseInfo"}
> 
> {"timestamp":1648986200961,"status":404,"error":"Not Found","message":"","path":"/api/rest_j/v1/dss/framework/workspace/workspaces/departments"}
> 
> ### Relevent platform
> centos7
> 
> ### Reproduction script
> null
> 
> ### Anything else
> _No response_
> 
> ### Are you willing to submit a PR?
> * [x]  Yes I am willing to submit a PR!

**Comment by zeronex98** [comment]
我也遇到同样的问题，请问是如何解决的？

**Comment by litongqian** [comment]
我也遇到这种情况,打断点没看出啥问题
