### ISSUE TITLE
[bug]Workspace management - user management, editing users, the interface reports 400bad request, the parameter username needs to be changed to camel case

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#594]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

工作空间管理-用户管理，编辑用户，接口报400bad request

参数username需修改成驼峰式
(Workspace management - user management, editing users, the interface reports 400bad request
The parameter username needs to be modified to camel case)

![image (47)](https://user-images.githubusercontent.com/67190698/170610197-121e45ca-c410-4b76-8f48-a69dfbb48fe1.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
