### ISSUE TITLE
[bug]Workspace management - User management - Enter the um account - Click query, the query results do not display the corresponding results

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#595]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

工作空间管理-用户管理，输入um账号，如stacyyan，点击查询，查询结果未展示相应结果

接口：/api/rest_j/v1/dss/framework/workspace/getWorkspaceUsers

接口返回了所有结果，并未单独返回查询结果
![image (47)](https://user-images.githubusercontent.com/67190698/170171561-0aebe986-ca53-4316-97c6-1a28f4168e94.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
