### ISSUE TITLE
[bug]On the management page of the workspace, create a real-name user and a "hudser" user, and no matching data is displayed.

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#596]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

工作空间管理页面，创建实名用户和hudser类用户，显示无匹配数据

创建实名用户：
![image (48)](https://user-images.githubusercontent.com/20251962/170685655-53b39513-3299-40ba-8b68-983a48dc4053.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
