### ISSUE TITLE
[bug]Workspace home page, no project creation function

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#597]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

工作空间首页，页面无创建工程功能
![image (45)](https://user-images.githubusercontent.com/20251962/170685868-04c9a408-badc-4edb-b54c-884f4f3a83d9.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
