### ISSUE TITLE
[bug]The interface of "/api/rest_j/v1/dss/framework/project/getDeletedProjects" display "bad req"

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#598]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
The interface of "/api/rest_j/v1/dss/framework/project/getDeletedProjects" display "bad req"
接口/api/rest_j/v1/dss/framework/project/getDeletedProjects，显示bad request

![image (50)](https://user-images.githubusercontent.com/20251962/170676836-d9878307-4121-4987-a518-83f3ce9f49aa.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
