### ISSUE TITLE
[bug]On the workflow version comparison page, a new node is added after the version is released, and the latest modification time of the node is displayed as "invalid date"

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#599]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
On the workflow version comparison page, a new node is added after the version is released, and the latest modification time of the node is displayed as "invalid date"
工作流版本比对页面，发版之后新增节点，显示节点最新修改时间为invalid date

![image (38)](https://user-images.githubusercontent.com/20251962/170676498-72a4485a-b42b-4ab8-a2b3-a9e352d7213b.png)
![image (39)](https://user-images.githubusercontent.com/20251962/170676509-0d6b1843-9910-4fd4-8573-b20fbac7a4f1.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
