### ISSUE TITLE
On the Create Project page, the drop-down boxes of publish permission, edit permission and view permission cannot obtain all users of the workspace

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#601]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
On the Create Project page, the drop-down boxes of publish permission, edit permission and view permission cannot obtain all users of the workspace
创建项目页面，发布权限、编辑权限和查看权限下拉框，未获取该工作空间全部用户

As follows:
如下图所示：
![image (40)](https://user-images.githubusercontent.com/20251962/170674925-28b196a0-641a-486f-a3de-c6090d34ffcd.png)

Edit permission drop-down box:
编辑权限下拉框：
![image (41)](https://user-images.githubusercontent.com/20251962/170674940-de8a55ed-c8e5-4b24-b934-8d492919ab16.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
