### ISSUE TITLE
Rolling back a workflow shows that the update is successful, but the open workflow does not display the latest workflow content synchronously

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#602]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
Rolling back a workflow shows that the update is successful, but the open workflow does not display the latest workflow content synchronously
回滚工作流，显示更新成功，但是已打开工作流没有同步显示最新工作流内容
![image (12)](https://user-images.githubusercontent.com/20251962/170674341-27526917-4db4-4037-a7bb-6b2fc4a7f1cf.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
