### ISSUE TITLE
Failed to rollback workflow with error

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#603]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
Failed to rollback workflow with error
Request URL:
api/rest_j/v1/dss/framework/orchestrator/rollbackOrchestrator

![image (16)](https://user-images.githubusercontent.com/20251962/170673693-6b9b821b-1e88-46ca-a46d-df90f7536056.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
