### ISSUE TITLE
After the workflow node re-associates the script, the content of the opened tab is not updated synchronously

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#604]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
After the workflow node re-associates the script, the content of the opened tab is not updated synchronously
工作流节点，重新关联脚本，已打开tab内容没有同步更新
![image (13)](https://user-images.githubusercontent.com/20251962/170672161-afb74593-8984-4118-bbe2-6a95b4817b3f.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
