### ISSUE TITLE
Workflow pauses execution interface and displays 404 

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#605]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
Workflow pauses execution interface and displays 404
工作流这块，工作流暂停执行接口，显示404
![image (15)](https://user-images.githubusercontent.com/20251962/170669282-59182564-f25b-4f93-bc42-a7253151b7fc.png)

`{"timestamp":1646121709789,"status":404,"error":"Not Found","message":"","path":"/api/rest_j/v1/entrance/exec_id017019dss-flow-entrancebdphdp11jobs01:9006flowexecution_stacyyan_flowexecution_5/kill"}`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
