### ISSUE TITLE
Excel file failed to import into hive in Workspace 

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#606]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
Excel file failed to import into hive in Workspace, and the interface of /api/rest_j/v1/filesystem/formate responses 500
工作空间excel文件导入hive失败

接口/api/rest_j/v1/filesystem/formate显示500
![image (22)](https://user-images.githubusercontent.com/67190698/170172623-4c5088c8-7d81-4cb6-95c2-6f4f60e5c334.png)

CSV file successed to import into hive in Workspace when using the interface of /api/filesystem/formate
工作空间csv文件导入hive，使用的是接口/api/filesystem/formate，是成功的

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Already fixed

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
