### ISSUE TITLE
Workspace management - Creating user interface, response "400Bad Request"

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#608]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

工作空间管理，创建用户接口，显示400Bad Request
![image (29)](https://user-images.githubusercontent.com/67190698/170172735-74604a16-facd-468d-b9c9-f1065413e754.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
