### ISSUE TITLE
Workspace management page - user management, the department returned by the user is inconsistent with the department set by the management desk - user management

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#609]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
Workspace management page - user management, the department returned by the user is inconsistent with the department set by the management desk - user management
(工作空间管理页面-用户管理，用户返回的部门和管理台-用户管理设置的部门不一致)

As follows:
(如下图所示)
![image (26)](https://user-images.githubusercontent.com/20251962/170707046-0b94bad2-3909-46d2-8398-6cfcf0b17d1c.png)
![image (27)](https://user-images.githubusercontent.com/20251962/170707062-f1c13d8b-4658-47c1-b95b-f66f67ad74e9.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
