### ISSUE TITLE
[bug]Workspace page, non-administrators can also create workspaces and access admin functions

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#610]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
Workspace page, non-administrators can also create workspaces and access admin functions
(工作空间页面，当前非管理员也可创建工作空间和进入管理员功能)

such "stacyyan"  non-administrators, it can crdate workspace, and entry management platform
(如：stacyyan，非管理员,可创建工作空间，也可进入管理台)
![image (31)](https://user-images.githubusercontent.com/20251962/170707662-efe978bf-8aea-4505-a92a-168946cd4202.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
