### ISSUE TITLE
The project tree display interface, when the workflow name exceeds a certain length, opening 10 workflows will exceed the scope of the interface

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#611]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
The project tree display interface, when the workflow name exceeds a certain length, opening 10 workflows will exceed the scope of the interface, as follows)
(工程树形显示界面，这里虽然控制了最多打开10个工作流tab，但是当工作流名字超一定长度时，打开10个工作流，会超出界面范围，如下图所示)
![image (17)](https://user-images.githubusercontent.com/67190698/170172875-6f75d574-42ec-4b56-8961-92ba1c5191ad.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
