### ISSUE TITLE
On the project page, from View Versions, open the latest version, and also display read-only mode

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#612]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
On the project page, from View Versions, open the latest version, and also display read-only mode
(工程页面，从查看版本里，打开最新的版本，也显示只读模式)
![image (34)](https://user-images.githubusercontent.com/20251962/170710015-730454de-d947-4bd4-9f56-156ba1f3c561.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
