### ISSUE TITLE
[bug]On the project page, click the page to add a workflow, select the project to which it belongs, and add a workflow. After success, it needs to be refreshed

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#614]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
On the project page, click the page to add a workflow, select the project to which it belongs, and add a workflow. After success, it needs to be refreshed
(工程页面，点击页面添加工作流，选择所属项目，添加工作流，成功后，需刷新页面，才会显示该工作流)
![image (43)](https://user-images.githubusercontent.com/20251962/170711074-10321d3d-dd5d-490c-8cff-e218588c1ace.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
