### ISSUE TITLE
[bug]Project page, configure project, configure different projects, all open the same project

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#615]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

工程页面，配置工程，配置不同的工程项目，打开的都是同一个工程项目
![image (35)](https://user-images.githubusercontent.com/67190698/170173049-428ead5d-4888-4b83-a08c-b8672ee5e2fb.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
