### ISSUE TITLE
Interface：/api/rest_j/v1/dss/framework/orchestrator/openOrchestrator，id transfer error

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#616]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
Interface：/api/rest_j/v1/dss/framework/orchestrator/openOrchestrator，id transfer error
(接口：/api/rest_j/v1/dss/framework/orchestrator/openOrchestrator，id传错)
![image (14)](https://user-images.githubusercontent.com/20251962/170711642-898fd972-0275-466c-b2d9-a8907b8f8fea.png)

{"method":null,"status":1,"message":"error code(错误码): 1000856, error message(错误信息): can not find orc from db for orcId: 283.","data":{"errorMsg":{"serviceKind":"dss-framework-orchestrator-server-dev","level":2,"port":9003,"errCode":1000856,"ip":"bdphdp11jobs01","desc":"can not find orc from db for orcId: 283"}}}

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
