### ISSUE TITLE
The tree-shaped project display interface. After the configuration project is successful, the page needs to be refreshed to sort in descending order according to the project modification time.

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#617]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
After the configuration project is successful, the page needs to be refreshed to sort in descending order according to the project modification time.
(配置工程后，需刷新页面，才根据工程修改时间降序排序)

As shown in the figure below, modify the item A_stacy_0228. After the modification, it is not ranked first, but the page needs to be refreshed to display it in the first position.
(如下图，修改项目A_stacy_0228，修改后，没有立刻排在第一位，而需刷新页面，才显示在第一位)
![image (18)](https://user-images.githubusercontent.com/20251962/170712517-da7a8105-926b-4124-b631-d0692b4008d1.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
