### ISSUE TITLE
Add a workflow, when the workflow name is repeated, click Confirm, the display name cannot be repeated, but the Confirm button keeps spinning and cannot be clicked

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#618]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
Add a workflow, when the workflow name is repeated, click Confirm, the display name cannot be repeated, but the Confirm button keeps spinning and cannot be clicked
(添加工作流，工作流名称重复时，点击确认，显示名称不可重复，但是确认按钮一直转圈，不可点击)
![image (33)](https://user-images.githubusercontent.com/20251962/170712900-41b048e1-b8a5-4c53-b71b-912ca7b20274.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
