### ISSUE TITLE
On the user management page, the interface shows that the total is 22, but there are only 7 user data. Click the second and third pages, and no data is displayed.

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#619]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
On the user management page, the interface shows that the total is 22, but there are only 7 user data. Click the second and third pages, and no data is displayed.
(用户管理页面，接口显示total为22条，但是只有7条用户数据，点击第二页和第三页，显示暂无数据)
![image (32)](https://user-images.githubusercontent.com/67190698/170173241-b467200c-dbee-4892-bd4a-75a0c0b9cfe9.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
