### ISSUE TITLE
The result set is downloaded as excel, it shows failure, and there is a problem with the server

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#620]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
The result set is downloaded as excel, it shows failure, and there is a problem with the server
(结果集下载为excel，显示失败，服务器出现问题)
![image (21)](https://user-images.githubusercontent.com/67190698/170173281-e8d4a967-71b8-49e6-a643-c05e8b796c21.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
