### ISSUE TITLE
The export of the result set to excel and csv fails, and the error is as follows

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#621]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
The export of the result set to excel and csv fails, and the error is as follows
(结果集导出为excel和csv失败，报错如下)
![image (20)](https://user-images.githubusercontent.com/20251962/170713798-683251b3-ec72-49f6-bf21-bc936d60d897.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
