### ISSUE TITLE
Right click on the table to export the table, select excel format to export, the export fails

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#622]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
Right click on the table to export the table, select excel format to export, the export fails
(表右键导出表，选择excel格式导出，导出失败)
![image (19)](https://user-images.githubusercontent.com/67190698/170173366-6ea4666b-bf0d-4fad-a04b-bfc6eadaad12.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
