### ISSUE TITLE
[bug]On the department and user management page, the time of creating a department is inaccurate, and the current actual time is not obtained

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#624]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
On the department and user management page, the time of creating a department is inaccurate, and the current actual time is not obtained
(部门和用户管理页面，创建部门的时间不准确，未获取当前实际时间)
![image (30)](https://user-images.githubusercontent.com/67190698/170173444-22e51f80-373d-4a18-a9eb-cb0b50bfb8bd.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
