### ISSUE TITLE
The sendemail node is sent to oa-test and the CC is empty.

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#731]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

![54](https://user-images.githubusercontent.com/67190698/170431028-a24f5af3-5bed-470a-b536-405e8b175f89.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
