### ISSUE TITLE
The errors reported by hive and spark are inconsistent

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#743]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

CREATE TABLE hduser05db.zhibiaoweidu_banen2(  zhibiaoweidu_banen bigint COMMENT 'zhibiaoweidu_banen')ROW FORMAT SERDE   'org.apache.hadoop.hive.ql.io.orc.OrcSerde' STORED AS INPUTFORMAT   'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat' OUTPUTFORMAT   'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'LOCATION  'viewfs://bdphdp11/user/hive/warehouse/thduser05/hduser05db.db/zhibiaoweidu_banen2'TBLPROPERTIES (  'orc.compress'='SNAPPY',   'transient_lastDdlTime'='1651804544')

Inconsistent execution error
(执行报错不一致)
![image (64)](https://user-images.githubusercontent.com/67190698/170432000-d70e8500-d150-4184-9d6c-cbea204db4be.png)
![image (65)](https://user-images.githubusercontent.com/67190698/170432006-f75a6f26-9fa5-412f-96d5-307775ddba9d.png)

hope
(期望)

The errors reported by hive and spark are inconsistent
(hive 和spark的报错最好能统一)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yuankang134** [comment]
dss-1.1.0 has sbsoved

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
