### ISSUE TITLE
发布一个脚本内容为空的sql，能发布成功 

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#755]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

【步骤】

发布一个脚本内容为空的sql，能发布成功
![image (82)](https://user-images.githubusercontent.com/67190698/170436892-b46d9e90-073d-4803-8ffe-8643064abf7d.png)
![image (83)](https://user-images.githubusercontent.com/67190698/170436904-3b1b325f-0c0d-4a0a-9416-5c5728497a28.png)

【期望】

发布失败，弹出提示

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yuankang134** [comment]
Dss-1.1.0 has solved

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
