### ISSUE TITLE
A large amount of data "Display", "Dashboard", "widget", failed to execute

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#814]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
sql executes 1000 items, the widget is bound to sql, and the widget is added to Display and Dashboard. Due to the large amount of data, the query fails and the execution fails.
(sql执行1000条，widget绑定sql，Display、Dashboard添加该widget，由于数据量大，导致查询失败，执行失败)
![image (17)](https://user-images.githubusercontent.com/20251962/170686560-a2facc97-7b0e-41c2-bdfe-9a15a7f3f9dc.png)
![image (18)](https://user-images.githubusercontent.com/20251962/170686569-a6c75d43-7aee-4a48-afec-5b5375e0c91d.png)
![image (19)](https://user-images.githubusercontent.com/20251962/170686573-ecd5f2e8-1bd5-4dc4-a014-3a90a1ab3f82.png)
![image (20)](https://user-images.githubusercontent.com/20251962/170686577-ca99c35d-e6b3-4701-8503-c798c43eb032.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
DSS1.1.0 has resolved this BUG.
