### ISSUE TITLE
The number of tasks displayed by the resource manager is inconsistent with the number of tasks displayed by the task manager

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#815]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description
The number of tasks displayed by the resource manager is inconsistent with the number of tasks displayed by the task manager (资源管理器显示的任务数同任务管理器展示的不一致).
![image (21)](https://user-images.githubusercontent.com/67190698/170448944-40ed9551-9dac-4cd7-b841-5e2a32d775ca.png)
![5](https://user-images.githubusercontent.com/67190698/170448976-9313c3fd-342d-4464-a57a-9552c8ebf16e.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wushengyeyouya** [comment]
DSS1.1.0 has resolved this BUG.
