### ISSUE TITLE
[Feature] [DSS-AppConn] Integrated Apache DolphinScheduler1.3.X, designed and developed a new scheduling center

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#848]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

Integrated Apache DolphinScheduler1.3.X, designed and developed a new scheduling center
(集成了 Apache DolphinScheduler1.3.X，设计并开发了全新的调度中心)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.0
