### ISSUE TITLE
[Feature] [DSS-Commons]Adapting three-party Components Apache Linkis1.1.1

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#849]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

Adapting three-party Components Apache Linkis1.1.1
(适配了 Apache Linkis1.1.1)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.0
