### ISSUE TITLE
[Feature] [DSS-AppConn] Integrated with Prophecis0.3.2

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#852]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

 Integrated with Prophecis0.3.2
(集成了 Prophecis0.3.2)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.0
