### ISSUE TITLE
[Feature] [DSS-Deployment] Support for elegant upgrades

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#862]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

Support for elegant upgrades
(支持优雅升级)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add it in DSS1.1.0
