### ISSUE TITLE
[Bug][DSS-Workspace] Fixed a problem where the visual interface was not displayed after clicking the visual button

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#874]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

Fixed a problem where the visual interface was not displayed after clicking the visual button
(修复点击可视化按钮后界面没有显示可视化界面的问题 )

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Fix it in DSS 1.1.0
