### ISSUE TITLE
[Feature] [DSS-Workspace] Fixed script copy and paste to first opened folder error

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#875]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

Fixed script copy and paste to first opened folder error
(修复脚本复制粘贴到首次打开的文件夹下报错的问题)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Fix it in DSS 1.1.0
