### ISSUE TITLE
[Bug] [DSS-Workflow] Fixed workflow node not being able to display the latest exception in directory when right-clicking key scripts

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#876]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

Fixed workflow node not being able to display the latest exception in directory when right-clicking key scripts
(修复工作流节点在右键关键脚本时，目录不能展示最新的异常)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Fix it in DSS 1.1.0
