### ISSUE TITLE
[Bug][DSS-Workflow] Fixed an issue that caused workflow to freeze when some nodes were successfully executed but the state was not reversed

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#877]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

Fixed an issue that caused workflow to freeze when some nodes were successfully executed but the state was not reversed
(修复工作流实时执行时部分节点已成功但状态未翻转导致工作流卡死的问题)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Fix it in DSS 1.1.0
