### ISSUE TITLE
[Bug] [DSS-Data Service] Fix the problem that no permission is displayed when exporting result sets in CSV format

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#878]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

Fix the problem that no permission is displayed when exporting result sets in CSV format
(修复导出CSV格式的结果集显示无权限问题)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Fix it in DSS 1.1.0
