### ISSUE TITLE
[Bug] [DSS-Commons] Fix shell calls to SQoop and script code inconsistency between code and script

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#879]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

Fix shell calls to SQoop and script code inconsistency between code and script
(修复shell中调用sqoop和script code中的代码与脚本中不一致问题)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Fix it in DSS 1.1.0
