### ISSUE TITLE
[Bug] [DSS-Commons] Fixed an issue where the script is always running and the engine is busy when the shell node enters the vi a.txt command

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#880]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

Fixed an issue where the script is always running and the engine is busy when the shell node enters the vi a.txt command
(修复shell节点输入vi a.txt命令会导致脚本一直运行且引擎处于繁忙的问题)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Fix it in DSS 1.1.0
