### ISSUE TITLE
[Feature] [DSS-Node] Support adding shell nodes.

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#881]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

[DSS-Node] Support adding shell nodes.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add in DSS 1.1.0
