### ISSUE TITLE
[Feature] [DSS-DB] After the user selects the corresponding table in the database, it is supported to choose to compress or grant it to other users.

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#882]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

After the user selects the corresponding table in the database, it is supported to choose to compress or grant it to other users.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add in DSS 1.1.0
