### ISSUE TITLE
[Feature] [DSS-Commons] Added DSS real-name user login function, it can switch to read-only users and record audit logs.

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#884]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

Added DSS real-name user login function, it can switch to read-only users and record audit logs.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add in DSS 1.1.0
