### ISSUE TITLE
[Feature] [DSS-Commons] Support history pages embedded in WTSS.

### ISSUE THREAD

**Issue by yuankang134** [WeBankFinTech/DataSphereStudio#885]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

Support history pages embedded in WTSS.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
Add in DSS 1.1.0
