### ISSUE TITLE
[Feature] 官方能不能提供一个docker包

### ISSUE THREAD

**Issue by Barbery** [WeBankFinTech/DataSphereStudio#908]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

整个安装非常繁琐，门槛太高，大家需要的是学习使用这个工具而不是怎么安装这个工具，强烈建议官方团队维护一个官方的docker包，方便大家一键安装

### Description

整个安装非常繁琐，门槛太高，大家需要的是学习使用这个工具而不是怎么安装这个工具，强烈建议官方团队维护一个官方的docker包，方便大家一键安装

### Use case

整个安装非常繁琐，门槛太高，大家需要的是学习使用这个工具而不是怎么安装这个工具，强烈建议官方团队维护一个官方的docker包，方便大家一键安装

### solutions

整个安装非常繁琐，门槛太高，大家需要的是学习使用这个工具而不是怎么安装这个工具，强烈建议官方团队维护一个官方的docker包，方便大家一键安装

### Anything else

整个安装非常繁琐，门槛太高，大家需要的是学习使用这个工具而不是怎么安装这个工具，强烈建议官方团队维护一个官方的docker包，方便大家一键安装

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by a1418692409** [comment]
支持，希望出1.1.0的安装简化版

**Comment by xjt1995** [comment]
支持

**Comment by wuqing0312** [comment]
支持

**Comment by zqburde** [comment]
you can find it. https://github.com/WeBankFinTech/WeDataSphere/tree/wds-hadoop2.7.2/docs/docker/hadoop2.7.2
