### ISSUE TITLE
./bin/install.sh中读到两条本机ip

### ISSUE THREAD

**Issue by 5herhom** [WeBankFinTech/DataSphereStudio#96]
https://github.com/WeBankFinTech/DataSphereStudio/blob/859b0bdee47a5c7801f66c22ee4ca42160dd91fc/bin/install.sh#L107
该行在这台CentOS Linux release 7.2.1511(Core)下返回了两条ip。
如图所示：
![image](https://user-images.githubusercontent.com/35916131/72882662-f28f5300-3d3d-11ea-9624-61eaab9fc2bb.png)

原因：这台机器执行ip addr时，172.17.0.1也满足这条awk，ip addr内容如下：
![image](https://user-images.githubusercontent.com/35916131/72882793-2d918680-3d3e-11ea-82b9-40bf77ae1173.png)

**Comment by peacewong** [comment]
This is a bug and the way to get the IP will be modified in subsequent versions

**Comment by 5herhom** [comment]
> This is a bug and the way to get the IP will be modified in subsequent versions

Thank you.
