### ISSUE TITLE
dss web无法跳转qualitis页面

### ISSUE THREAD

**Issue by KangTomwk** [WeBankFinTech/DataSphereStudio#969]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar feature requirement.

### Problem Description

qualitis接入dss后，无法从dss web上跳转到qualitis页面，没有显示的可跳转的地方

### Description

qualitis：0.9.2，dss：1.1.0，linkis：1.1.0

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zqburde** [comment]
请参加 https://github.com/WeBankFinTech/DataSphereStudio/issues/954
