### ISSUE TITLE
[Bug] dss jumps to other pages and password-free is invalid

### ISSUE THREAD

**Issue by hunter-cloud09** [WeBankFinTech/DataSphereStudio#984]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar issues.

### DSS Component

dss-appconn

### What happened + What you expected to happen

In the dss page, after the configuration of DS, exchangis, and qualitis is completed, password-free jumps cannot be performed when jumping to these pages, but this situation only occurs when the first jump is made. After the first login, the second jump No need for a password
![image](https://user-images.githubusercontent.com/53144338/202095591-241946d7-df7d-4a99-aa8a-e17938cbe78d.png)
![image](https://user-images.githubusercontent.com/53144338/202095778-1556feb7-f3d3-4eb7-bb9b-69fe9f9dff90.png)

### Relevent platform

dss 1.1.0 exchangis 0.9.2 DS 1.3.x ...

### Reproduction script

just jump to other pages in dss

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by RainbowWS** [comment]
I also have this problem.

**Comment by zqburde** [comment]
该问题会在DSS1.1.1开源版本中修复，预计会在11月29号左右发布
